// Sentences for the "Sentences" mode: translate Turkish into English by arranging word tiles.
// Format: [level, turkish, english, ...alternatives]
//   level: "e" = easy, "m" = medium, "h" = hard
//   english: the answer, words separated by spaces, no final punctuation.
//            The tiles are made from these words; "let's" and "o'clock" are single tiles.
//   alternatives: other accepted word orders (they may only use words from the answer).
const SENTENCES = [
  // ---------- Easy ----------
  ["e", "Evet, biliyorum.", "yes I know"],
  ["e", "Hayır, bilmiyorum.", "no I do not know"],
  ["e", "Ben iyiyim.", "I am fine"],
  ["e", "Sen nasılsın?", "how are you"],
  ["e", "Bu ne?", "what is this"],
  ["e", "Bu kim?", "who is this"],
  ["e", "O nerede?", "where is he"],
  ["e", "Su istiyorum.", "I want water"],
  ["e", "Kahve istiyorum.", "I want coffee"],
  ["e", "Çay ister misin?", "do you want tea"],
  ["e", "Ben gidiyorum.", "I am going"],
  ["e", "Geliyorum!", "I am coming"],
  ["e", "Lütfen bekle.", "please wait", "wait please"],
  ["e", "Çok teşekkür ederim.", "thank you very much"],
  ["e", "Bu çok güzel.", "this is very beautiful"],
  ["e", "Hava soğuk.", "the weather is cold"],
  ["e", "Hava çok sıcak.", "the weather is very hot"],
  ["e", "Ben açım.", "I am hungry"],
  ["e", "Sen haklısın.", "you are right"],
  ["e", "Bu doğru.", "this is true"],
  ["e", "Bu yanlış.", "this is wrong"],
  ["e", "Benim adım Ali.", "my name is Ali"],
  ["e", "Senin adın ne?", "what is your name"],
  ["e", "Ben doktorum.", "I am a doctor"],
  ["e", "O bir doktor.", "he is a doctor"],
  ["e", "Bu benim evim.", "this is my house"],
  ["e", "Bu benim arabam.", "this is my car"],
  ["e", "Bu senin kitabın mı?", "is this your book"],
  ["e", "Annem evde.", "my mother is at home"],
  ["e", "Babam işte.", "my father is at work"],
  ["e", "Kız çok mutlu.", "the girl is very happy"],
  ["e", "Çocuklar okulda.", "the children are at school"],
  ["e", "Köpek nerede?", "where is the dog"],
  ["e", "Kapıyı kapat.", "close the door"],
  ["e", "Kapıyı aç.", "open the door"],
  ["e", "Buraya gel.", "come here"],
  ["e", "Eve git.", "go home"],
  ["e", "Eve gidelim.", "let's go home"],
  ["e", "Hadi gidelim!", "come on let's go"],
  ["e", "Seni seviyorum.", "I love you"],
  ["e", "Onu tanıyorum.", "I know him"],
  ["e", "Beni dinle.", "listen to me"],
  ["e", "Bana bak.", "look at me"],
  ["e", "Bana yardım et.", "help me"],
  ["e", "Yardıma ihtiyacım var.", "I need help"],
  ["e", "Paraya ihtiyacım var.", "I need money"],
  ["e", "Param yok.", "I do not have money"],
  ["e", "Zamanım yok.", "I do not have time"],
  ["e", "Bir sorun var.", "there is a problem"],
  ["e", "Sorun yok.", "no problem"],
  ["e", "Her şey yolunda.", "everything is fine"],
  ["e", "Ne yapıyorsun?", "what are you doing"],
  ["e", "Ne istiyorsun?", "what do you want"],
  ["e", "Nereye gidiyorsun?", "where are you going"],
  ["e", "Nereden geliyorsun?", "where are you coming from"],
  ["e", "Sen kimsin?", "who are you"],
  ["e", "Bu ne demek?", "what does this mean"],
  ["e", "Anlamıyorum.", "I do not understand"],
  ["e", "Ben de!", "me too"],
  ["e", "Tamam, gidelim.", "okay let's go"],
  ["e", "Yarın görüşürüz.", "see you tomorrow"],
  ["e", "Sonra görüşürüz.", "see you later"],
  ["e", "Bugün çok mutluyum.", "I am very happy today", "today I am very happy"],
  ["e", "Ben evdeyim.", "I am at home"],
  ["e", "Neredesin?", "where are you"],
  ["e", "Buradayım.", "I am here"],
  ["e", "Saat kaç?", "what time is it"],
  ["e", "Bir dakika bekle.", "wait a minute"],
  ["e", "Çok güzelsin.", "you are very beautiful"],
  ["e", "Bu kitap çok iyi.", "this book is very good"],
  ["e", "Yemek hazır.", "the food is ready"],
  ["e", "Ben hazırım.", "I am ready"],
  ["e", "Hazır mısın?", "are you ready"],
  ["e", "Emin misin?", "are you sure"],
  ["e", "Eminim.", "I am sure"],
  ["e", "Ciddi misin?", "are you serious"],
  ["e", "Bu çok komik.", "this is very funny"],
  ["e", "Hiç para yok.", "there is no money"],
  ["e", "Kimse yok.", "there is nobody"],
  ["e", "Herkes burada.", "everyone is here"],
  ["e", "Su soğuk.", "the water is cold"],
  ["e", "Kahve sıcak.", "the coffee is hot"],
  ["e", "Oda temiz.", "the room is clean"],
  ["e", "Ev büyük.", "the house is big"],
  ["e", "Araba yeni.", "the car is new"],
  ["e", "Bu eski bir araba.", "this is an old car"],
  ["e", "Polis geldi.", "the police came"],
  ["e", "Kardeşim burada.", "my brother is here"],
  ["e", "Arkadaşım geliyor.", "my friend is coming"],
  ["e", "Onlar nerede?", "where are they"],
  ["e", "Biz buradayız.", "we are here"],
  ["e", "Gece çok soğuk.", "the night is very cold"],
  ["e", "Bugün pazar.", "today is Sunday"],
  ["e", "Yarın cuma.", "tomorrow is Friday"],
  ["e", "Dün cumartesiydi.", "yesterday was Saturday"],
  ["e", "Geç kaldım.", "I am late"],
  ["e", "Acele et!", "hurry up"],
  ["e", "Dikkat et!", "be careful"],
  ["e", "Merak etme.", "do not worry"],
  ["e", "Özür dilerim.", "I am sorry"],
  ["e", "İyi geceler.", "good night"],
  ["e", "Günaydın, anne.", "good morning mom"],
  ["e", "İyi akşamlar.", "good evening"],
  ["e", "Ben yemek yiyorum.", "I am eating"],
  ["e", "Su içiyorum.", "I am drinking water"],
  ["e", "Kitap okuyorum.", "I am reading a book"],
  ["e", "Mektup yazıyorum.", "I am writing a letter"],
  ["e", "Müzik dinliyorum.", "I am listening to music"],
  ["e", "Ne düşünüyorsun?", "what do you think"],
  ["e", "Ne oldu?", "what happened"],
  ["e", "Ne dedin?", "what did you say"],
  ["e", "Kim geldi?", "who came"],
  ["e", "Ne zaman geliyorsun?", "when are you coming"],
  ["e", "Neden buradasın?", "why are you here"],
  ["e", "Bu benim hatam.", "this is my mistake"],
  ["e", "Kapı açık.", "the door is open"],
  ["e", "Kapı kapalı.", "the door is closed"],
  ["e", "Beni ara.", "call me"],
  ["e", "Seni arayacağım.", "I will call you"],
  ["e", "Şimdi gitmeliyim.", "I have to go now", "now I have to go"],
  ["e", "Biraz bekle.", "wait a little"],
  ["e", "Bir kahve, lütfen.", "a coffee please"],
  ["e", "İki çay, lütfen.", "two teas please"],
  ["e", "Türkçe öğreniyorum.", "I am learning Turkish"],
  ["e", "Türkçe biliyor musun?", "do you know Turkish"],
  ["e", "Biraz Türkçe biliyorum.", "I know a little Turkish"],
  ["e", "İngilizce konuşuyor musun?", "do you speak English"],
  ["e", "Yavaş konuş, lütfen.", "speak slowly please", "please speak slowly"],
  ["e", "Bugün çok güzel bir gün.", "today is a very beautiful day"],
  ["e", "Kedi uyuyor.", "the cat is sleeping"],
  ["e", "Bebek uyuyor.", "the baby is sleeping"],
  ["e", "Annem çok güzel.", "my mother is very beautiful"],
  ["e", "Babam doktor.", "my father is a doctor"],
  ["e", "Ailem burada.", "my family is here"],
  ["e", "Bu senin için.", "this is for you"],
  ["e", "Bu bizim evimiz.", "this is our house"],
  ["e", "Onların arabası yeni.", "their car is new"],
  ["e", "Kahve sever misin?", "do you like coffee"],
  ["e", "Çay severim.", "I like tea"],
  ["e", "Balık sevmiyorum.", "I do not like fish"],
  ["e", "Kırmızı araba benim.", "the red car is mine"],
  ["e", "Mavi kapıyı aç.", "open the blue door"],
  ["e", "Siyah köpek benim.", "the black dog is mine"],
  ["e", "Okul uzak mı?", "is the school far"],
  ["e", "Ev yakın.", "the house is near"],
  ["e", "Kolay değil.", "it is not easy"],
  ["e", "Çok zor.", "it is very difficult"],
  ["e", "Bu imkansız.", "this is impossible"],
  ["e", "Bu harika bir fikir.", "this is a great idea"],
  ["e", "Yağmur yağıyor.", "it is raining"],
  ["e", "Hasta mısın?", "are you sick"],
  ["e", "Hastayım.", "I am sick"],
  ["e", "Korkuyorum.", "I am scared"],
  ["e", "Korkma.", "do not be afraid"],
  ["e", "Gitme!", "do not go"],
  ["e", "Yapma!", "do not do that"],
  ["e", "Otur, lütfen.", "sit down please", "please sit down"],
  ["e", "Ayağa kalk.", "stand up"],
  ["e", "Bana söyle.", "tell me"],
  ["e", "Doğruyu söyle.", "tell the truth"],
  ["e", "Yalan söyleme.", "do not lie"],
  ["e", "Sana söz veriyorum.", "I promise you"],
  ["e", "Sana inanıyorum.", "I believe you"],
  ["e", "Sana güveniyorum.", "I trust you"],
  ["e", "Beni unutma.", "do not forget me"],
  ["e", "Seni özledim.", "I missed you"],
  ["e", "Hepsi bu.", "that is all"],
  ["e", "Bu ne kadar?", "how much is this"],
  ["e", "Kaç yaşındasın?", "how old are you"],
  ["e", "Yirmi yaşındayım.", "I am twenty years old"],
  ["e", "Bu bir sır.", "this is a secret"],
  ["e", "Bunu kim yaptı?", "who did this"],
  ["e", "Sorun ne?", "what is the problem"],
  ["e", "Bir sorunumuz var.", "we have a problem"],
  ["e", "Hayat çok kısa.", "life is very short"],
  ["e", "Bu çay çok sıcak.", "this tea is very hot"],
  ["e", "Evli misin?", "are you married"],
  ["e", "Nerede yaşıyorsun?", "where do you live"],
  ["e", "Gözlerini kapat.", "close your eyes"],
  ["e", "Ellerini yıka.", "wash your hands"],
  ["e", "Bugün benim doğum günüm.", "today is my birthday"],
  ["e", "Kimse mükemmel değildir.", "nobody is perfect"],
  ["e", "Bir şey sorabilir miyim?", "can I ask something"],
  ["e", "Ne demek istiyorsun?", "what do you mean"],

  // ---------- Medium ----------
  ["m", "Yarın sabah okula gideceğim.", "I will go to school tomorrow morning", "tomorrow morning I will go to school"],
  ["m", "Dün akşam ne yaptın?", "what did you do yesterday evening"],
  ["m", "Bu kitabı okumak istiyorum.", "I want to read this book"],
  ["m", "Seninle konuşmak istiyorum.", "I want to talk to you"],
  ["m", "Benimle gelmek ister misin?", "do you want to come with me"],
  ["m", "Neden bana söylemedin?", "why did you not tell me"],
  ["m", "Ne dediğini anlamadım.", "I did not understand what you said"],
  ["m", "Onun nerede olduğunu biliyorum.", "I know where he is"],
  ["m", "Ne yapacağımı bilmiyorum.", "I do not know what to do"],
  ["m", "Bunu yapmak zorundayım.", "I have to do this"],
  ["m", "Bunu yapamam.", "I cannot do this"],
  ["m", "Sana yardım edebilirim.", "I can help you"],
  ["m", "Bana yardım edebilir misin?", "can you help me"],
  ["m", "Gitmemiz gerekiyor.", "we need to go"],
  ["m", "Burada ne yapıyorsun?", "what are you doing here"],
  ["m", "Babam doktor, annem öğretmen.", "my father is a doctor and my mother is a teacher"],
  ["m", "Annem mutfakta yemek yapıyor.", "my mother is cooking in the kitchen"],
  ["m", "Arkadaşım yarın gelecek.", "my friend will come tomorrow", "tomorrow my friend will come"],
  ["m", "Dün gece çok güzel bir rüya gördüm.", "I had a very beautiful dream last night", "last night I had a very beautiful dream"],
  ["m", "Bu sabah kahve içtim.", "I drank coffee this morning", "this morning I drank coffee"],
  ["m", "Her sabah çay içerim.", "I drink tea every morning", "every morning I drink tea"],
  ["m", "Bu akşam evde kalacağım.", "I will stay at home this evening", "this evening I will stay at home"],
  ["m", "Yarın hava güzel olacak.", "the weather will be nice tomorrow", "tomorrow the weather will be nice"],
  ["m", "Telefonumu bulamıyorum.", "I cannot find my phone"],
  ["m", "Paramı kaybettim.", "I lost my money"],
  ["m", "Bu kadın kim?", "who is this woman"],
  ["m", "Kapıdaki adam kim?", "who is the man at the door"],
  ["m", "Masadaki kitap benim.", "the book on the table is mine"],
  ["m", "Dün okuduğum kitap çok güzeldi.", "the book I read yesterday was very good"],
  ["m", "Türkçe bilen biri var mı?", "is there someone who knows Turkish"],
  ["m", "Eve gelince beni ara.", "call me when you come home", "when you come home call me"],
  ["m", "Yemekten sonra yürüyelim.", "let's walk after dinner", "after dinner let's walk"],
  ["m", "Hiçbir şey anlamadım.", "I did not understand anything"],
  ["m", "Kimseye söyleme.", "do not tell anyone"],
  ["m", "Kimseye söylemeyeceğim.", "I will not tell anyone"],
  ["m", "Seni çok özledim.", "I missed you very much"],
  ["m", "Seni asla unutmayacağım.", "I will never forget you"],
  ["m", "Bunu bir daha asla yapmayacağım.", "I will never do this again"],
  ["m", "Bu benim en iyi arkadaşım.", "this is my best friend"],
  ["m", "En sevdiğim renk mavi.", "my favorite color is blue"],
  ["m", "Kardeşim benden büyük.", "my brother is older than me"],
  ["m", "Bu araba o arabadan daha hızlı.", "this car is faster than that car"],
  ["m", "İstanbul çok büyük bir şehir.", "Istanbul is a very big city"],
  ["m", "Türkiye'de yaşıyorum.", "I live in Turkey"],
  ["m", "Londra'dan geldim.", "I came from London"],
  ["m", "Saat beşte buluşalım.", "let's meet at five o'clock"],
  ["m", "Saat kaçta geleceksin?", "what time will you come"],
  ["m", "Üç gün sonra döneceğim.", "I will come back in three days"],
  ["m", "İki yıldır burada yaşıyorum.", "I have been living here for two years"],
  ["m", "Dün okula gitmedim.", "I did not go to school yesterday", "yesterday I did not go to school"],
  ["m", "Hasta olduğu için gelmedi.", "he did not come because he was sick", "because he was sick he did not come"],
  ["m", "İstersen seninle gelirim.", "if you want I will come with you", "I will come with you if you want"],
  ["m", "Keşke burada olsaydın.", "I wish you were here"],
  ["m", "Param olsaydı bir araba alırdım.", "if I had money I would buy a car", "I would buy a car if I had money"],
  ["m", "Çok çalışmalısın.", "you must work hard"],
  ["m", "Daha erken gelmeliydin.", "you should have come earlier"],
  ["m", "Biraz daha kalabilir misin?", "can you stay a little longer"],
  ["m", "Bu gece dışarı çıkalım.", "let's go out tonight", "tonight let's go out"],
  ["m", "Bu filmi daha önce gördüm.", "I have seen this movie before"],
  ["m", "Bu şarkıyı çok seviyorum.", "I love this song very much"],
  ["m", "Onun ne dediğini duydun mu?", "did you hear what he said"],
  ["m", "Sana bir şey sormak istiyorum.", "I want to ask you something"],
  ["m", "Sana bir şey söyleyeceğim.", "I will tell you something"],
  ["m", "Bunu neden yaptın?", "why did you do this"],
  ["m", "Ne olduğunu bilmiyorum.", "I do not know what happened"],
  ["m", "Bana ne olduğunu anlat.", "tell me what happened"],
  ["m", "Polis evin önünde bekliyor.", "the police are waiting in front of the house"],
  ["m", "Çocuklar bahçede oynuyor.", "the children are playing in the garden"],
  ["m", "Kedi yatağın altında.", "the cat is under the bed"],
  ["m", "Kitap çantanın içinde.", "the book is in the bag"],
  ["m", "Araba evin arkasında.", "the car is behind the house"],
  ["m", "Okul evimizin yanında.", "the school is next to our house"],
  ["m", "Yemek yemeden önce ellerini yıka.", "wash your hands before eating"],
  ["m", "Annemle babam evde değil.", "my mother and father are not at home"],
  ["m", "Kız kardeşim doktor olmak istiyor.", "my sister wants to be a doctor"],
  ["m", "Erkek kardeşim on yaşında.", "my brother is ten years old"],
  ["m", "Bu soruya cevap veremem.", "I cannot answer this question"],
  ["m", "Hiç vaktim yok.", "I have no time"],
  ["m", "Acele etmemiz lazım.", "we need to hurry"],
  ["m", "Geç kaldık, acele et!", "we are late hurry up"],
  ["m", "Merak etme, her şey yolunda.", "do not worry everything is fine"],
  ["m", "Ne kadar zamandır buradasın?", "how long have you been here"],
  ["m", "Bunu duyduğuma çok sevindim.", "I am very glad to hear this"],
  ["m", "Tanıştığımıza memnun oldum.", "nice to meet you"],
  ["m", "Benim adım Ayşe, senin adın ne?", "my name is Ayşe what is your name"],
  ["m", "Bu sabah çok erken kalktım.", "I got up very early this morning", "this morning I got up very early"],
  ["m", "Her gün işe gidiyorum.", "I go to work every day", "every day I go to work"],
  ["m", "Hafta sonu ne yapacaksın?", "what will you do on the weekend"],
  ["m", "Gelecek hafta İstanbul'a gidiyoruz.", "we are going to Istanbul next week", "next week we are going to Istanbul"],
  ["m", "Geçen yıl Türkiye'ye gittim.", "I went to Turkey last year", "last year I went to Turkey"],
  ["m", "Bu dünyada hiçbir şey kolay değil.", "nothing is easy in this world", "in this world nothing is easy"],
  ["m", "Seni seven biri var.", "there is someone who loves you"],
  ["m", "Kimse beni anlamıyor.", "nobody understands me"],
  ["m", "Herkes seni arıyor.", "everyone is looking for you"],
  ["m", "Onu bulmak zorundayız.", "we have to find him"],
  ["m", "Kapıyı kim açtı?", "who opened the door"],
  ["m", "Telefonu açmadı.", "he did not answer the phone"],
  ["m", "Seni bekliyordum.", "I was waiting for you"],
  ["m", "Sabahtan beri seni arıyorum.", "I have been looking for you since morning"],
  ["m", "Bunu sana daha önce söylemiştim.", "I had told you this before"],
  ["m", "Beni bekleme.", "do not wait for me"],
  ["m", "Biraz su alabilir miyim?", "can I have some water"],
  ["m", "Bir bardak su, lütfen.", "a glass of water please"],
  ["m", "Şekersiz kahve istiyorum.", "I want coffee without sugar"],
  ["m", "Bu ev bizim için çok küçük.", "this house is too small for us"],
  ["m", "Yeni bir araba aldım.", "I bought a new car"],
  ["m", "Bunu nereden aldın?", "where did you buy this"],
  ["m", "Ne kadar paraya ihtiyacın var?", "how much money do you need"],
  ["m", "Bu benim için çok önemli.", "this is very important for me"],
  ["m", "Onun için her şeyi yaparım.", "I would do everything for him"],
  ["m", "Hangi gün geliyorsun?", "which day are you coming"],
  ["m", "Ne zaman döneceksin?", "when will you come back"],
  ["m", "Çok geç oldu, eve gitmeliyim.", "it is very late I have to go home"],
  ["m", "Bu yol şehre gidiyor.", "this road goes to the city"],
  ["m", "Polis katili yakaladı.", "the police caught the killer"],
  ["m", "Adam kapıyı açıp içeri girdi.", "the man opened the door and went inside"],
  ["m", "Kız gülerek odaya girdi.", "the girl entered the room laughing"],
  ["m", "Yürürken müzik dinlerim.", "I listen to music while walking", "while walking I listen to music"],
  ["m", "Okumayı çok severim.", "I like reading very much"],
  ["m", "Türkçe öğrenmek kolay değil.", "learning Turkish is not easy"],
  ["m", "Türkçe öğrenmek için buradayım.", "I am here to learn Turkish"],
  ["m", "Her şey için teşekkür ederim.", "thank you for everything"],
  ["m", "Yardımın için teşekkürler.", "thanks for your help"],
  ["m", "Geldiğin için teşekkürler.", "thanks for coming"],
  ["m", "Geç kaldığım için özür dilerim.", "I am sorry for being late"],
  ["m", "Benim hatamdı, özür dilerim.", "it was my mistake I am sorry"],
  ["m", "Bunu yapmana gerek yok.", "you do not need to do this"],
  ["m", "Bence o haklı.", "I think he is right"],
  ["m", "Sence bu doğru mu?", "do you think this is true"],
  ["m", "Bence bu iyi bir fikir değil.", "I think this is not a good idea"],
  ["m", "Sanırım yanlış yoldayız.", "I think we are on the wrong road"],
  ["m", "Galiba yağmur yağacak.", "I think it will rain"],
  ["m", "Belki yarın gelirim.", "maybe I will come tomorrow"],
  ["m", "Muhtemelen evdedir.", "he is probably at home"],
  ["m", "Herhalde unuttu.", "he probably forgot"],
  ["m", "Ne zamandır Türkçe öğreniyorsun?", "how long have you been learning Turkish"],
  ["m", "Hiç İstanbul'a gittin mi?", "have you ever been to Istanbul"],
  ["m", "Daha önce hiç böyle bir şey görmedim.", "I have never seen anything like this before"],
  ["m", "Söylediğim her şeyi unut.", "forget everything I said"],
  ["m", "İstediğin her şeyi alabilirsin.", "you can take everything you want"],
  ["m", "Gördüğün adam benim babam.", "the man you saw is my father"],
  ["m", "Burada çalışan herkes çok iyi.", "everyone who works here is very nice"],
  ["m", "Yarın ne olacağını kimse bilmiyor.", "nobody knows what will happen tomorrow"],
  ["m", "Onun geleceğini sanmıyorum.", "I do not think he will come"],
  ["m", "Bana gerçeği söylemeni istiyorum.", "I want you to tell me the truth"],
  ["m", "Gitmeni istemiyorum.", "I do not want you to go"],
  ["m", "Kalmanı istiyorum.", "I want you to stay"],
  ["m", "Yemeğin hazır olduğunu söyledi.", "he said that the food is ready", "he said the food is ready"],
  ["m", "Saat on ikide yatarım.", "I go to bed at twelve o'clock"],
  ["m", "Yazın deniz çok güzel.", "the sea is very beautiful in summer", "in summer the sea is very beautiful"],
  ["m", "Kışın çok kar yağar.", "it snows a lot in winter", "in winter it snows a lot"],
  ["m", "Bugün hava çok güzel, dışarı çıkalım.", "the weather is very nice today let's go out"],
  ["m", "Benim de bir köpeğim var.", "I also have a dog"],
  ["m", "Kaç kardeşin var?", "how many siblings do you have"],
  ["m", "İki erkek kardeşim var.", "I have two brothers"],
  ["m", "Hiç çocuğun var mı?", "do you have any children"],
  ["m", "Evet, evliyim ve iki çocuğum var.", "yes I am married and I have two children"],
  ["m", "Hangi dilleri konuşuyorsun?", "which languages do you speak"],
  ["m", "Türkçeyi nerede öğrendin?", "where did you learn Turkish"],
  ["m", "Bunu Türkçe nasıl söylerim?", "how do I say this in Turkish"],
  ["m", "Bu kelime ne anlama geliyor?", "what does this word mean"],
  ["m", "Lütfen daha yavaş konuşur musunuz?", "could you speak more slowly please", "could you please speak more slowly"],
  ["m", "Ne demek istediğini anlamadım.", "I did not understand what you mean"],
  ["m", "Arabayla mı geldin?", "did you come by car"],
  ["m", "Otobüsle işe gidiyorum.", "I go to work by bus"],
  ["m", "Bu akşam bize gel.", "come to our house this evening", "this evening come to our house"],
  ["m", "Yemek çok lezzetliydi, teşekkürler.", "the food was very delicious thanks"],
  ["m", "Annemi her gün ararım.", "I call my mother every day", "every day I call my mother"],
  ["m", "Babam her sabah gazete okur.", "my father reads the newspaper every morning", "every morning my father reads the newspaper"],
  ["m", "Çocuklar okuldan geldi mi?", "did the children come from school"],
  ["m", "Neden bu kadar geç kaldın?", "why are you so late"],
  ["m", "Ödevimi henüz bitirmedim.", "I have not finished my homework yet"],
  ["m", "Film saat sekizde başlıyor.", "the movie starts at eight o'clock"],
  ["m", "Lütfen bu kapıyı açmayın.", "please do not open this door"],
  ["m", "Bütün gün evde kaldım.", "I stayed at home all day"],
  ["m", "Kardeşimle birlikte yaşıyorum.", "I live together with my brother"],
  ["m", "Bu kadar güzel bir yer görmedim.", "I have not seen such a beautiful place"],
  ["m", "Onu dün gece gördüm.", "I saw him last night", "last night I saw him"],

  // ---------- Easy: everyday words (words-extra.js) ----------
  ["e", "Ekmek ve peynir istiyorum.", "I want bread and cheese"],
  ["e", "Süt soğuk.", "the milk is cold"],
  ["e", "Bu elma çok tatlı.", "this apple is very sweet"],
  ["e", "Muz sever misin?", "do you like bananas"],
  ["e", "Çorba çok sıcak.", "the soup is very hot"],
  ["e", "Salata taze.", "the salad is fresh"],
  ["e", "Kahvaltı hazır.", "breakfast is ready"],
  ["e", "Hesap, lütfen.", "the bill please"],
  ["e", "Garson nerede?", "where is the waiter"],
  ["e", "Menüyü görebilir miyim?", "can I see the menu"],
  ["e", "Bir bardak süt, lütfen.", "a glass of milk please"],
  ["e", "Çatal nerede?", "where is the fork"],
  ["e", "Yemek çok lezzetli.", "the food is very delicious"],
  ["e", "Çok acıktım.", "I am very hungry"],
  ["e", "Çok susadım.", "I am very thirsty"],
  ["e", "Mutfak temiz.", "the kitchen is clean"],
  ["e", "Pencereyi aç.", "open the window"],
  ["e", "Pencereyi kapat.", "close the window"],
  ["e", "Masa çok büyük.", "the table is very big"],
  ["e", "Sandalyeye otur.", "sit on the chair"],
  ["e", "Anahtarım nerede?", "where is my key"],
  ["e", "Banyo nerede?", "where is the bathroom"],
  ["e", "Tuvalet nerede?", "where is the toilet"],
  ["e", "Bahçe çok güzel.", "the garden is very beautiful"],
  ["e", "Komşumuz çok nazik.", "our neighbor is very kind"],
  ["e", "Çantam çok ağır.", "my bag is very heavy"],
  ["e", "Gözlüğüm nerede?", "where are my glasses"],
  ["e", "Şemsiyeni al.", "take your umbrella"],
  ["e", "Başım ağrıyor.", "my head hurts"],
  ["e", "Dişim ağrıyor.", "my tooth hurts"],
  ["e", "Çok yorgunum.", "I am very tired"],
  ["e", "İlacını al.", "take your medicine"],
  ["e", "Eczane nerede?", "where is the pharmacy"],
  ["e", "Hastane uzak mı?", "is the hospital far"],
  ["e", "Bebek ağlıyor.", "the baby is crying"],
  ["e", "Kız gülüyor.", "the girl is laughing"],
  ["e", "Çocuklar uyuyor.", "the children are sleeping"],
  ["e", "Yüzünü yıka.", "wash your face"],
  ["e", "Ceketini giy.", "put on your jacket"],
  ["e", "Ayakkabılarını çıkar.", "take off your shoes"],
  ["e", "Dedem çok yaşlı.", "my grandfather is very old"],
  ["e", "Büyükannem bahçede.", "my grandmother is in the garden"],
  ["e", "Teyzem İstanbul'da yaşıyor.", "my aunt lives in Istanbul"],
  ["e", "Ablam öğretmen.", "my older sister is a teacher"],
  ["e", "Abim doktor.", "my older brother is a doctor"],
  ["e", "Kuzenim burada.", "my cousin is here"],
  ["e", "Babam mühendis.", "my father is an engineer"],
  ["e", "Annem hemşire.", "my mother is a nurse"],
  ["e", "Ben öğrenciyim.", "I am a student"],
  ["e", "Öğretmen sınıfta.", "the teacher is in the classroom"],
  ["e", "Ödevim bitti.", "my homework is finished"],
  ["e", "Yarın sınavım var.", "I have an exam tomorrow", "tomorrow I have an exam"],
  ["e", "Kalemin var mı?", "do you have a pen"],
  ["e", "Defterimi unuttum.", "I forgot my notebook"],
  ["e", "Kütüphane kapalı.", "the library is closed"],
  ["e", "Köprü çok uzun.", "the bridge is very long"],
  ["e", "Otel nerede?", "where is the hotel"],
  ["e", "Müze açık mı?", "is the museum open"],
  ["e", "Otobüs geliyor.", "the bus is coming"],
  ["e", "Bilet ne kadar?", "how much is the ticket"],
  ["e", "Pasaportum nerede?", "where is my passport"],
  ["e", "Tatildeyim.", "I am on holiday"],
  ["e", "Havalimanı uzak.", "the airport is far"],
  ["e", "Dağ çok yüksek.", "the mountain is very high"],
  ["e", "Orman çok büyük.", "the forest is very big"],
  ["e", "Ağaç çok uzun.", "the tree is very tall"],
  ["e", "Bu çiçek çok güzel.", "this flower is very beautiful"],
  ["e", "Göl çok derin.", "the lake is very deep"],
  ["e", "Gökyüzü mavi.", "the sky is blue"],
  ["e", "Bugün hava güneşli.", "the weather is sunny today", "today the weather is sunny"],
  ["e", "Rüzgar çok soğuk.", "the wind is very cold"],
  ["e", "Kar yağıyor.", "it is snowing"],
  ["e", "Kışı severim.", "I like winter"],
  ["e", "Sonbahar geldi.", "autumn has come"],
  ["e", "Dağda kar var.", "there is snow on the mountain"],
  ["e", "Kedim çok tembel.", "my cat is very lazy"],
  ["e", "İnek süt verir.", "the cow gives milk"],
  ["e", "Aslan çok güçlü.", "the lion is very strong"],
  ["e", "Kuşlar uçuyor.", "the birds are flying"],
  ["e", "Bugün pazartesi.", "today is Monday"],
  ["e", "Yarın salı.", "tomorrow is Tuesday"],
  ["e", "Dün çarşambaydı.", "yesterday was Wednesday"],
  ["e", "Doğum günüm mayısta.", "my birthday is in May"],
  ["e", "Doğum günüm ekimde.", "my birthday is in October"],
  ["e", "Kırmızı elbiseyi beğendim.", "I liked the red dress"],
  ["e", "Bu gömlek çok pahalı.", "this shirt is very expensive"],
  ["e", "Bu şapka ucuz.", "this hat is cheap"],
  ["e", "Pantolonum kirli.", "my trousers are dirty"],
  ["e", "Kazağını giy.", "put on your sweater"],
  ["e", "Nakit ödeyeceğim.", "I will pay in cash"],
  ["e", "Alışverişe gidiyorum.", "I am going shopping"],
  ["e", "Çok heyecanlıyım.", "I am very excited"],
  ["e", "Neden sinirlisin?", "why are you angry"],
  ["e", "Endişeli görünüyorsun.", "you look worried"],
  ["e", "Sıkıldım.", "I am bored"],
  ["e", "Seni özlüyorum.", "I miss you"],
  ["e", "Bu filmi beğendim.", "I liked this movie"],
  ["e", "Yüzmeyi severim.", "I like swimming"],
  ["e", "Futbol oynuyorlar.", "they are playing football"],
  ["e", "Gazete okuyorum.", "I am reading the newspaper"],
  ["e", "Bilgisayarım çalışmıyor.", "my computer is not working"],
  ["e", "İnternet yok.", "there is no internet"],
  ["e", "Bana mesaj at.", "send me a message"],
  ["e", "Afiyet olsun!", "enjoy your meal"],
  ["e", "Geçmiş olsun.", "get well soon"],
  ["e", "İyi şanslar!", "good luck"],
  ["e", "Rica ederim.", "you are welcome"],
  ["e", "Maalesef gelemem.", "unfortunately I cannot come"],
  ["e", "Neyse ki erken geldin.", "fortunately you came early"],

  // ---------- Medium: everyday words (words-extra.js) ----------
  ["m", "Kahvaltıda ekmek, peynir ve zeytin yerim.", "I eat bread cheese and olives for breakfast", "for breakfast I eat bread cheese and olives"],
  ["m", "Akşam yemeğinde ne var?", "what is for dinner"],
  ["m", "Annem mutfakta çorba pişiriyor.", "my mother is cooking soup in the kitchen"],
  ["m", "Marketten süt ve yumurta aldım.", "I bought milk and eggs from the market"],
  ["m", "Bu restoran çok pahalı ama yemekleri çok lezzetli.", "this restaurant is very expensive but the food is very delicious"],
  ["m", "Garson, bir şişe su getirir misiniz?", "waiter could you bring a bottle of water"],
  ["m", "Hesabı ben ödeyeceğim.", "I will pay the bill"],
  ["m", "Dondurmayı buzdolabına koy.", "put the ice cream in the fridge"],
  ["m", "Çok acıktım, bir şey yiyelim.", "I am very hungry let's eat something"],
  ["m", "Kahvemi şekersiz içerim.", "I drink my coffee without sugar"],
  ["m", "Domatesleri ve soğanları kes.", "cut the tomatoes and onions"],
  ["m", "Bu meyveler çok taze.", "these fruits are very fresh"],
  ["m", "Evimizde üç yatak odası var.", "there are three bedrooms in our house"],
  ["m", "Anahtarlarımı masanın üstüne koydum.", "I put my keys on the table"],
  ["m", "Kitaplar dolabın içinde.", "the books are in the cupboard"],
  ["m", "Bahçede çok güzel çiçekler var.", "there are very beautiful flowers in the garden"],
  ["m", "Yeni bir ev kiraladık.", "we rented a new house"],
  ["m", "Komşumuz bize yardım etti.", "our neighbor helped us"],
  ["m", "Banyoda sabun yok.", "there is no soap in the bathroom"],
  ["m", "Odamı temizlemem lazım.", "I need to clean my room"],
  ["m", "Dün gece iyi uyuyamadım.", "I could not sleep well last night", "last night I could not sleep well"],
  ["m", "Her sabah yedide uyanırım.", "I wake up at seven every morning", "every morning I wake up at seven"],
  ["m", "Başım çok ağrıyor, ilaç lazım.", "my head hurts a lot I need medicine"],
  ["m", "Doktora gitmen gerekiyor.", "you need to go to the doctor"],
  ["m", "Hemşire hastaya ilaç verdi.", "the nurse gave medicine to the patient", "the nurse gave the patient medicine"],
  ["m", "Grip oldum, evde dinleniyorum.", "I have the flu I am resting at home"],
  ["m", "Sağlıklı olmak için spor yapmalısın.", "you should do sports to be healthy"],
  ["m", "Çocuk düştü ve ağlamaya başladı.", "the child fell and started to cry"],
  ["m", "Bu şakaya herkes güldü.", "everyone laughed at this joke"],
  ["m", "Kazağını giy, dışarısı çok soğuk.", "put on your sweater it is very cold outside"],
  ["m", "Büyükannem ve dedem köyde yaşıyor.", "my grandmother and grandfather live in the village"],
  ["m", "Ablam geçen yıl evlendi.", "my older sister got married last year", "last year my older sister got married"],
  ["m", "Kuzenim üniversitede okuyor.", "my cousin is studying at university"],
  ["m", "Babam bir şirkette mühendis olarak çalışıyor.", "my father works as an engineer at a company"],
  ["m", "Öğretmenimiz bize çok ödev verdi.", "our teacher gave us a lot of homework"],
  ["m", "Yarınki sınav için ders çalışmalıyım.", "I have to study for tomorrow's exam"],
  ["m", "Kütüphaneden iki kitap aldım.", "I took two books from the library"],
  ["m", "Bu cümleyi Türkçeye çevirebilir misin?", "can you translate this sentence into Turkish"],
  ["m", "Bu kelimeyi hatırlamıyorum.", "I do not remember this word"],
  ["m", "Toplantı saat üçte başlayacak.", "the meeting will start at three o'clock"],
  ["m", "Müşteri müdürle konuşmak istiyor.", "the customer wants to talk to the manager"],
  ["m", "Otobüs durağı köprünün yanında.", "the bus stop is next to the bridge"],
  ["m", "Müzeye nasıl gidebilirim?", "how can I go to the museum"],
  ["m", "Havalimanına taksiyle gittik.", "we went to the airport by taxi"],
  ["m", "Bileti internetten aldım.", "I bought the ticket online"],
  ["m", "Bu sokakta güzel bir kafe var.", "there is a nice cafe on this street"],
  ["m", "Tatilde denize gitmek istiyorum.", "I want to go to the sea on holiday"],
  ["m", "Yazın Türkiye'ye seyahat edeceğiz.", "we will travel to Turkey in summer", "in summer we will travel to Turkey"],
  ["m", "Otelimiz plaja çok yakın.", "our hotel is very close to the beach"],
  ["m", "Bisikletle işe gidiyorum.", "I go to work by bicycle"],
  ["m", "Metroda telefonumu kaybettim.", "I lost my phone on the metro"],
  ["m", "Haritaya bak, kaybolduk.", "look at the map we are lost"],
  ["m", "Yarın yağmur yağacak, şemsiyeni unutma.", "it will rain tomorrow do not forget your umbrella"],
  ["m", "Kışın hava çok soğuk olur.", "the weather is very cold in winter", "in winter the weather is very cold"],
  ["m", "İlkbaharda çiçekler açar.", "flowers bloom in spring", "in spring flowers bloom"],
  ["m", "Gökyüzünde hiç bulut yok.", "there are no clouds in the sky"],
  ["m", "Göle yürüyelim mi?", "shall we walk to the lake"],
  ["m", "Köpek bahçede koşuyor.", "the dog is running in the garden"],
  ["m", "Kedi ağacın üstünde.", "the cat is in the tree"],
  ["m", "Kuşlar ağaçta şarkı söylüyor.", "the birds are singing in the tree"],
  ["m", "Aslanlar ve ayılar çok tehlikeli hayvanlardır.", "lions and bears are very dangerous animals"],
  ["m", "Okullar eylülde açılıyor.", "schools open in September"],
  ["m", "Her cumartesi pazara gideriz.", "we go to the market every Saturday", "every Saturday we go to the market"],
  ["m", "Perşembe günü toplantımız var.", "we have a meeting on Thursday"],
  ["m", "Hafta sonu ne yaptın?", "what did you do at the weekend"],
  ["m", "Öğleden sonra parkta yürüdük.", "we walked in the park in the afternoon", "in the afternoon we walked in the park"],
  ["m", "Gece yarısı eve döndüm.", "I came home at midnight", "at midnight I came home"],
  ["m", "Saat iki buçukta buluşalım.", "let's meet at half past two"],
  ["m", "Bu elbise bana çok dar.", "this dress is too tight for me"],
  ["m", "Bu ayakkabılar çok rahat.", "these shoes are very comfortable"],
  ["m", "Mavi gömleği mi beyaz gömleği mi alayım?", "should I buy the blue shirt or the white shirt"],
  ["m", "İndirimde güzel bir ceket buldum.", "I found a nice jacket on sale"],
  ["m", "Kırk lira ödedim.", "I paid forty lira"],
  ["m", "Biraz daha ucuz bir şey var mı?", "is there something a little cheaper"],
  ["m", "Kredi kartı kabul ediyor musunuz?", "do you accept credit cards"],
  ["m", "Sınavı geçince çok sevindim.", "I was very happy when I passed the exam", "when I passed the exam I was very happy"],
  ["m", "Ona yalan söylediğim için özür diledim.", "I apologized for lying to him"],
  ["m", "Bu sorunu birlikte çözebiliriz.", "we can solve this problem together"],
  ["m", "Karar vermek çok zor.", "it is very difficult to decide"],
  ["m", "Hangisini seçeceğimi bilmiyorum.", "I do not know which one to choose"],
  ["m", "Bunu bir kez daha deneyelim.", "let's try this one more time"],
  ["m", "Işığı kapatır mısın?", "can you turn off the light"],
  ["m", "Bilgisayarımı kullanabilirsin.", "you can use my computer"],
  ["m", "Bana bir e-posta gönder.", "send me an email"],
  ["m", "Arkadaşlarımı doğum günüme davet ettim.", "I invited my friends to my birthday"],
  ["m", "Hediyeyi kutuya koydum.", "I put the gift in the box"],
  ["m", "Bayramda ailemi ziyaret ettim.", "I visited my family on the holiday"],
  ["m", "Kardeşimle aynı odada uyuyorum.", "I sleep in the same room as my brother"],
  ["m", "Gençken çok spor yapardım.", "I used to do a lot of sports when I was young", "when I was young I used to do a lot of sports"],
  ["m", "Çocukluğum bu köyde geçti.", "I spent my childhood in this village"],
  ["m", "Eskiden burada bir orman vardı.", "there used to be a forest here"],
  ["m", "Maalesef bugün çok meşgulüm.", "unfortunately I am very busy today", "unfortunately today I am very busy"],
  ["m", "Neyse ki kimse yaralanmadı.", "fortunately nobody was hurt"],
  ["m", "Hızlıca kahvaltı yapıp çıktım.", "I had a quick breakfast and left"],
  ["m", "Lütfen sessizce konuşun, bebek uyuyor.", "please speak quietly the baby is sleeping"],
  ["m", "Bu yüzden geç kaldım.", "that is why I was late"],
  ["m", "Yağmur yağdığı için evde kaldık.", "we stayed at home because it was raining", "because it was raining we stayed at home"],

  // ---------- Hard ----------
  ["h", "Dün akşam okuduğum kitabı sana yarın getireceğim.", "tomorrow I will bring you the book I read last night"],
  ["h", "Eğer yarın hava güzel olursa, denize gitmeyi düşünüyoruz.", "if the weather is nice tomorrow we are thinking of going to the sea", "we are thinking of going to the sea if the weather is nice tomorrow"],
  ["h", "Türkiye'ye geldiğimden beri her gün biraz Türkçe öğreniyorum.", "since I came to Turkey I have been learning a little Turkish every day", "I have been learning a little Turkish every day since I came to Turkey"],
  ["h", "Annemin bana verdiği yüzüğü kaybettiğimi ona söyleyemedim.", "I could not tell my mother that I lost the ring she gave me", "I could not tell my mother I lost the ring she gave me"],
  ["h", "Bu kadar çok çalışmasaydın, sınavı geçemezdin.", "if you had not studied so much you could not have passed the exam", "you could not have passed the exam if you had not studied so much"],
  ["h", "Telefonumu evde unuttuğum için seni arayamadım.", "I could not call you because I forgot my phone at home", "because I forgot my phone at home I could not call you"],
  ["h", "Kapıyı kimin açtığını hâlâ bilmiyoruz.", "we still do not know who opened the door"],
  ["h", "Doktor, bu ilacı günde üç kez almam gerektiğini söyledi.", "the doctor said that I have to take this medicine three times a day", "the doctor said I have to take this medicine three times a day"],
  ["h", "Yağmur durunca dışarı çıkıp parkta yürüyüş yapacağız.", "when the rain stops we will go out and take a walk in the park", "we will go out and take a walk in the park when the rain stops"],
  ["h", "Çocukken her yaz büyükannemin köyüne giderdik.", "when I was a child we used to go to my grandmother's village every summer", "we used to go to my grandmother's village every summer when I was a child"],
  ["h", "Bu evi satın almak için yıllarca para biriktirdiler.", "they saved money for years to buy this house"],
  ["h", "Ne kadar çok çalışırsan o kadar çok öğrenirsin.", "the more you study the more you learn"],
  ["h", "Sana söylediklerimi kimseye anlatmamanı istiyorum.", "I want you not to tell anyone what I told you"],
  ["h", "Toplantı iptal edildiği için bugün evden çalışacağım.", "I will work from home today because the meeting was cancelled", "because the meeting was cancelled I will work from home today"],
  ["h", "Arabamı tamir ettirmem gerekiyor ama hiç param yok.", "I need to get my car repaired but I have no money"],
  ["h", "Gelmeden önce beni arasaydın, seni havalimanında beklerdim.", "if you had called me before coming I would have waited for you at the airport", "I would have waited for you at the airport if you had called me before coming"],
  ["h", "Bu şehirde yaşayan insanların çoğu İngilizce bilmiyor.", "most of the people who live in this city do not know English", "most people who live in this city do not know English"],
  ["h", "Kardeşim, tatilden döndükten sonra yeni bir işe başlayacak.", "my brother will start a new job after he comes back from holiday", "after he comes back from holiday my brother will start a new job"],
  ["h", "Dün gece o kadar yorgundum ki yemek yemeden uyudum.", "last night I was so tired that I slept without eating", "I was so tired last night that I slept without eating"],
  ["h", "Bana yardım ettiğin için sana ne kadar teşekkür etsem azdır.", "I cannot thank you enough for helping me"],
  ["h", "Okuldan eve dönerken eski bir arkadaşıma rastladım.", "I ran into an old friend while I was coming home from school", "while I was coming home from school I ran into an old friend"],
  ["h", "Polis, hırsızın arka kapıdan kaçtığını düşünüyor.", "the police think that the thief escaped through the back door", "the police think the thief escaped through the back door"],
  ["h", "Bu mektubu kimin yazdığını öğrenmek istiyorum.", "I want to find out who wrote this letter"],
  ["h", "Keşke çocukken daha çok kitap okusaydım.", "I wish I had read more books when I was a child"],
  ["h", "Annem, akşam yemeği hazır olunca bizi çağıracağını söyledi.", "my mother said that she would call us when dinner was ready", "my mother said she would call us when dinner was ready"],
  ["h", "Bu filmi daha önce izlemiş olmalıyım, sonunu hatırlıyorum.", "I must have watched this movie before I remember the end"],
  ["h", "Babam, gençken çok iyi futbol oynarmış.", "apparently my father used to play football very well when he was young", "my father apparently used to play football very well when he was young"],
  ["h", "Komşumuzun köpeği bütün gece havladığı için hiç uyuyamadık.", "we could not sleep at all because our neighbor's dog barked all night", "because our neighbor's dog barked all night we could not sleep at all"],
  ["h", "İstanbul'a gittiğimde mutlaka o müzeyi ziyaret edeceğim.", "when I go to Istanbul I will definitely visit that museum", "I will definitely visit that museum when I go to Istanbul"],
  ["h", "Hangi otobüse binmem gerektiğini bilmediğim için taksiye bindim.", "I took a taxi because I did not know which bus I should take", "because I did not know which bus I should take I took a taxi"],
  ["h", "Bu soruyu cevaplayabilen tek öğrenci Ayşe'ydi.", "Ayşe was the only student who could answer this question", "the only student who could answer this question was Ayşe"],
  ["h", "Hasta olduğunu bilseydim, sana çorba getirirdim.", "if I had known that you were sick I would have brought you soup", "I would have brought you soup if I had known that you were sick", "if I had known you were sick I would have brought you soup", "I would have brought you soup if I had known you were sick"],
  ["h", "Yeni evimiz eskisinden daha büyük ama okula daha uzak.", "our new house is bigger than the old one but further from the school"],
  ["h", "Bu yemeği nasıl yaptığını bana öğretir misin?", "can you teach me how you made this food"],
  ["h", "Saat yedide kalkmış olsaydım otobüsü kaçırmazdım.", "if I had got up at seven I would not have missed the bus", "I would not have missed the bus if I had got up at seven"],
  ["h", "Her sabah işe gitmeden önce yarım saat yürürüm.", "every morning I walk for half an hour before I go to work", "I walk for half an hour every morning before I go to work"],
  ["h", "Bu konuda ne düşündüğünü öğrenmek isterim.", "I would like to know what you think about this"],
  ["h", "Onun bu kadar kızacağını tahmin etmemiştim.", "I had not expected him to get so angry"],
  ["h", "Bütün gün yağmur yağmasına rağmen maç iptal edilmedi.", "although it rained all day the match was not cancelled", "the match was not cancelled although it rained all day"],
  ["h", "Ödevini bitirmeden televizyon izlemene izin vermeyeceğim.", "I will not let you watch television before you finish your homework"],
  ["h", "Bu kitabı okuduktan sonra hayata farklı bakmaya başladım.", "after reading this book I started to look at life differently", "I started to look at life differently after reading this book"],
  ["h", "Seninle tanıştığım günü hiç unutmayacağım.", "I will never forget the day I met you"],
  ["h", "Bana ne olduğunu anlatmazsan sana yardım edemem.", "if you do not tell me what happened I cannot help you", "I cannot help you if you do not tell me what happened"],
  ["h", "Bu kadar güzel bir yerde yaşadığın için çok şanslısın.", "you are very lucky because you live in such a beautiful place"],
  ["h", "Mektubu aldığında bana haber ver.", "let me know when you receive the letter", "when you receive the letter let me know"],
  ["h", "Patronum, raporu yarın sabaha kadar bitirmemi istiyor.", "my boss wants me to finish the report by tomorrow morning"],
  ["h", "Bu ülkede yaşamaya başladığımdan beri çok şey öğrendim.", "I have learned a lot since I started living in this country", "since I started living in this country I have learned a lot"],
  ["h", "Annemle babam evlendiklerinde çok gençlermiş.", "apparently my mother and father were very young when they got married", "my mother and father were apparently very young when they got married"],
  ["h", "Çocuklar, bahçede oynarken pencereyi kırdılar.", "the children broke the window while they were playing in the garden", "while they were playing in the garden the children broke the window"],
  ["h", "Eve geldiğimde herkes çoktan uyumuştu.", "when I came home everyone had already fallen asleep", "everyone had already fallen asleep when I came home"],
  ["h", "Ne zaman ararsam arayayım, telefonunu hiç açmıyorsun.", "whenever I call you never answer your phone", "you never answer your phone whenever I call"],
  ["h", "Bu kadar geç kalacağını bilseydim seni beklemezdim.", "if I had known you would be so late I would not have waited for you", "I would not have waited for you if I had known you would be so late"],
  ["h", "Kız kardeşim doktor olmak için yıllarca çalıştı.", "my sister studied for years to become a doctor"],
  ["h", "Türkçe konuşurken hata yapmaktan korkmamalısın.", "you should not be afraid of making mistakes while speaking Turkish", "while speaking Turkish you should not be afraid of making mistakes"],
  ["h", "Bu, hayatımda yediğim en lezzetli yemekti.", "this was the most delicious meal I have ever eaten in my life"],
  ["h", "Yarın erken kalkmam gerektiği için bu gece erken yatacağım.", "I will go to bed early tonight because I have to get up early tomorrow", "because I have to get up early tomorrow I will go to bed early tonight"],
  ["h", "Arkadaşım, beni partiye davet etmeyi unuttuğunu söyledi.", "my friend said that he forgot to invite me to the party", "my friend said he forgot to invite me to the party"],
  ["h", "Bu dili öğrenmek sandığımdan çok daha zor.", "learning this language is much harder than I thought"],
  ["h", "Polis gelmeden önce hırsız çoktan kaçmıştı.", "the thief had already escaped before the police came", "before the police came the thief had already escaped"],
  ["h", "Senin yerinde olsam, bu teklifi kabul ederdim.", "if I were you I would accept this offer", "I would accept this offer if I were you"],
  ["h", "Hiç kimse ona inanmadı çünkü daha önce de yalan söylemişti.", "nobody believed him because he had lied before too"],
  ["h", "Akşam yemeğini hazırlarken müzik dinlemeyi severim.", "I like to listen to music while I am preparing dinner", "while I am preparing dinner I like to listen to music"],
  ["h", "Kardeşim sınavı geçtiğini öğrenince sevinçten ağladı.", "when my brother found out that he passed the exam he cried with joy", "my brother cried with joy when he found out that he passed the exam"],
  ["h", "Bu kadar çok insanın beni tanıdığını bilmiyordum.", "I did not know that so many people knew me", "I did not know so many people knew me"],
  ["h", "Babam, ben doğmadan önce bu şehirde öğretmenlik yapıyormuş.", "apparently my father worked as a teacher in this city before I was born", "my father apparently worked as a teacher in this city before I was born"],
  ["h", "Kim olduğunu söylemezsen kapıyı açmayacağım.", "if you do not say who you are I will not open the door", "I will not open the door if you do not say who you are"],
  ["h", "Onun söylediği hiçbir şeye inanmıyorum.", "I do not believe anything he says"],
  ["h", "Daha önce hiç bu kadar güzel bir gün batımı görmemiştim.", "I had never seen such a beautiful sunset before"],
  ["h", "Yeni bir dil öğrenmek, yeni bir dünyaya kapı açmak gibidir.", "learning a new language is like opening a door to a new world"],
  ["h", "Herkesin konuştuğu o filmi henüz izlemedim.", "I have not watched that movie everyone is talking about yet", "I have not yet watched that movie everyone is talking about"],
  ["h", "Trenin kaçta kalktığını bilen var mı?", "does anyone know what time the train leaves"],
  ["h", "Sokakta yürürken birinin beni takip ettiğini hissettim.", "while I was walking on the street I felt that someone was following me", "I felt that someone was following me while I was walking on the street", "while I was walking on the street I felt someone was following me", "I felt someone was following me while I was walking on the street"],
  ["h", "Arabayla gitseydik şimdiye kadar varmıştık.", "if we had gone by car we would have arrived by now", "we would have arrived by now if we had gone by car"],
  ["h", "Annem bana her zaman dürüst olmamı söylerdi.", "my mother always used to tell me to be honest"],
  ["h", "Ne yaparsan yap, asla pes etme.", "whatever you do never give up"],
  ["h", "Odadan çıkmadan önce ışıkları kapatmayı unutma.", "do not forget to turn off the lights before you leave the room", "before you leave the room do not forget to turn off the lights"],
  ["h", "Seni bu kadar mutlu gördüğüme çok sevindim.", "I am very glad to see you so happy"],
  ["h", "Bu işi bitirmek için en az iki haftaya ihtiyacımız var.", "we need at least two weeks to finish this job"],
  ["h", "Benimle evlenmek istediğini söylediğinde çok şaşırdım.", "I was very surprised when he said that he wanted to marry me", "I was very surprised when he said he wanted to marry me"],
  ["h", "Gördüğün gibi her şey yolunda.", "as you can see everything is fine"],
  ["h", "Duyduğuma göre yeni bir iş bulmuşsun.", "I heard that you found a new job", "I heard you found a new job"],
  ["h", "Söylediklerini anlamak için onu iki kez dinlemem gerekti.", "I had to listen to him twice to understand what he said"],
  ["h", "Ne kadar uğraşırsam uğraşayım bu kapıyı açamıyorum.", "no matter how hard I try I cannot open this door", "I cannot open this door no matter how hard I try"],
  ["h", "Bu kitabın yazarı, kitabı yazmak için on yıl harcamış.", "the author of this book apparently spent ten years writing it"],
  ["h", "Doktor olsaydım insanlara yardım edebilirdim.", "if I were a doctor I could help people", "I could help people if I were a doctor"],
  ["h", "Çocukların güvenliği için bu kapı her zaman kapalı tutulmalı.", "this door must always be kept closed for the safety of the children"],
  ["h", "Bu kadar pahalı olduğunu bilseydim almazdım.", "if I had known it was so expensive I would not have bought it", "I would not have bought it if I had known it was so expensive"],
  ["h", "Birbirimizi yıllardır tanıyoruz ama hiç kavga etmedik.", "we have known each other for years but we have never fought"],
  ["h", "Saatlerce bekledikten sonra sonunda otobüs geldi.", "after waiting for hours the bus finally came"],
  ["h", "Sana yalan söylediğimi düşünüyorsan yanılıyorsun.", "if you think that I lied to you you are wrong", "you are wrong if you think that I lied to you", "if you think I lied to you you are wrong", "you are wrong if you think I lied to you"],
  ["h", "Bu soruların hepsini cevaplamak zorunda değilsin.", "you do not have to answer all of these questions", "you do not have to answer all these questions"],
  ["h", "Hayatımda hiç bu kadar korktuğumu hatırlamıyorum.", "I do not remember ever being so scared in my life"],
  ["h", "Kitapçıdan aldığım sözlük çok işime yarıyor.", "the dictionary I bought from the bookstore is very useful to me"],
  ["h", "Ders bittikten sonra öğretmenle konuşmak istiyorum.", "I want to talk to the teacher after the lesson ends", "after the lesson ends I want to talk to the teacher"],
  ["h", "Bütün gün bilgisayar başında çalıştığım için gözlerim ağrıyor.", "my eyes hurt because I worked at the computer all day", "because I worked at the computer all day my eyes hurt"],
  ["h", "Kırmızı ışıkta durmayan araba bir kazaya neden oldu.", "the car that did not stop at the red light caused an accident"],
  ["h", "Yazın sıcak olmasına rağmen kışın çok kar yağar.", "although it is hot in summer it snows a lot in winter"],
  ["h", "Kaybettiğin anahtarları buldum, masanın altındaydı.", "I found the keys you lost they were under the table"],
  ["h", "Bu kadar çok insanın gelmesini beklemiyorduk.", "we were not expecting so many people to come"],
  ["h", "Bize yardım etmek isteyen herkese teşekkür ederiz.", "we thank everyone who wants to help us"],
  ["h", "Toplantıda söylenenleri anlamadıysan bana sorabilirsin.", "if you did not understand what was said in the meeting you can ask me", "you can ask me if you did not understand what was said in the meeting"],
  ["h", "Gece geç saatte dışarı çıkmanın tehlikeli olduğunu düşünüyorum.", "I think that it is dangerous to go out late at night", "I think it is dangerous to go out late at night"],
  ["h", "Şirketimiz geçen yıl yüzlerce yeni çalışan işe aldı.", "our company hired hundreds of new employees last year", "last year our company hired hundreds of new employees"],
  ["h", "Türkçeyi bu kadar iyi konuştuğunu bilmiyordum.", "I did not know you spoke Turkish so well"],
  ["h", "Yarın hava nasıl olursa olsun yürüyüşe çıkacağız.", "whatever the weather is like tomorrow we will go for a walk", "we will go for a walk tomorrow whatever the weather is like"],
  ["h", "Eskiden sigara içerdim ama iki yıl önce bıraktım.", "I used to smoke but I quit two years ago"],
  ["h", "İnsanlar onu tanıdıkça daha çok seviyorlar.", "the more people get to know him the more they like him"],
  ["h", "Pasaportumu kaybettiğimi havalimanına varınca fark ettim.", "I realized that I had lost my passport when I arrived at the airport", "when I arrived at the airport I realized that I had lost my passport"],
  ["h", "Bu elbiseyi düğün için almıştım ama hiç giymedim.", "I had bought this dress for the wedding but I never wore it"],
  ["h", "Ben gelene kadar hiçbir şeye dokunmayın.", "do not touch anything until I come", "until I come do not touch anything"],
  ["h", "Dün gördüğümüz ev, bugün gördüğümüzden daha güzeldi.", "the house we saw yesterday was more beautiful than the one we saw today"],
  ["h", "Bu kadar yorgun olmasaydım seninle sinemaya gelirdim.", "if I were not so tired I would come to the cinema with you", "I would come to the cinema with you if I were not so tired"],
  ["h", "Hastanede yatan arkadaşımı ziyaret etmeye gidiyorum.", "I am going to visit my friend who is in the hospital"],
  ["h", "Dışarısı o kadar soğuktu ki ellerimi hissedemiyordum.", "it was so cold outside that I could not feel my hands"],
  ["h", "Kimse ne olduğunu tam olarak bilmiyor.", "nobody knows exactly what happened"],
  ["h", "Kendini kötü hissediyorsan bugün işe gitme.", "if you feel bad do not go to work today", "do not go to work today if you feel bad"],
  ["h", "Bu şarkıyı her duyduğumda çocukluğumu hatırlarım.", "every time I hear this song I remember my childhood", "I remember my childhood every time I hear this song"],
  ["h", "Bütün paramı harcadığım için tatile gidemedim.", "I could not go on holiday because I spent all my money", "because I spent all my money I could not go on holiday"],
  ["h", "Geç kalırsan seni beklemeden gideriz.", "if you are late we will go without waiting for you", "we will go without waiting for you if you are late"],
  ["h", "Onunla konuştuktan sonra kendimi çok daha iyi hissettim.", "after talking to him I felt much better", "I felt much better after talking to him"],
  ["h", "Bu kelimenin ne anlama geldiğini sözlükte aradım.", "I looked up what this word means in the dictionary"],
];
