// Turkish words with English meanings.
//
// Part 1 (1883 words): the most common Turkish words, in frequency order (from film subtitles).
//   Source: https://docs.google.com/spreadsheets/d/1aOWAXLyrF74WAh53xDEtZLj62bHCiMHeGRfamXtRrsc
//   Based on Hermit Dave's frequency list (https://invokeit.wordpress.com/frequency-word-lists/).
//   Meanings revised, corrected and extended by Zilvinas S (2026).
// Part 2 (500 words): everyday words in dictionary form, added by Zilvinas S (2026).
//
// This whole file is licensed under CC BY-SA 3.0 (https://creativecommons.org/licenses/by-sa/3.0/),
// unlike the rest of the project — see LICENSE.
//
// Format: [turkish, english]. Separate alternative translations with "/" — any of them counts as correct.
// The first meaning is the main one. e.g. ["güzel", "beautiful/pretty"]

// Number of frequency-ranked words at the start of the list; everyday words follow.
const FREQUENT_WORD_COUNT = 1883;

const WORDS = [
  ["bir", "one/a/an/once/only"],
  ["bu", "this/this one"],
  ["ve", "and"],
  ["ne", "what/how/neither"],
  ["için", "for/in order to/because of"],
  ["çok", "a lot/very/many/much/too much"],
  ["ben", "I/me"],
  ["o", "he/she/it/that"],
  ["evet", "yes"],
  ["de", "also/too/as well/and/but"],
  ["var", "there is/there are/exists/have"],
  ["ama", "but"],
  ["mı", "is it/question particle"],
  ["değil", "not/is not/isn't"],
  ["hayır", "no"],
  ["sen", "you"],
  ["şey", "thing/stuff/um"],
  ["da", "also/too/as well/and/in/at"],
  ["daha", "more/yet/still/else"],
  ["bana", "to me/me/for me"],
  ["kadar", "until/as much as/as far as/up to/as/about"],
  ["seni", "you"],
  ["beni", "me"],
  ["iyi", "good/well/fine/nice"],
  ["onu", "him/her/it/that"],
  ["tamam", "ok/okay/alright/fine/done"],
  ["bunu", "this"],
  ["gibi", "like/as/such as/as if"],
  ["yok", "no/there isn't/there is not/none/absent/doesn't exist"],
  ["benim", "my/mine/I am"],
  ["her", "every/each/all"],
  ["sana", "to you/you/for you"],
  ["ki", "that/so that/which/who"],
  ["sadece", "only/just/merely"],
  ["neden", "why/reason/cause"],
  ["senin", "your/yours"],
  ["burada", "here"],
  ["zaman", "time/when"],
  ["hiç", "never/ever/none/at all/nothing/any"],
  ["şimdi", "now"],
  ["nasıl", "how"],
  ["sonra", "later/after/then/afterwards"],
  ["olduğunu", "that it is/that he is/that she is/that/being"],
  ["en", "most/the most/width"],
  ["hadi", "come on/let's/go on"],
  ["misin", "are you"],
  ["şu", "that/this"],
  ["öyle", "like that/so/such/that way"],
  ["ya", "or/what about/oh/yes"],
  ["güzel", "beautiful/pretty/nice/lovely/good"],
  ["biraz", "a little/a bit/some/little"],
  ["musun", "are you"],
  ["önce", "before/first/ago/earlier"],
  ["lütfen", "please"],
  ["İyi", "good/well/fine/nice"],
  ["bak", "look/see"],
  ["ona", "him/her/it/to him/to her/to it"],
  ["böyle", "like this/so/such/this way"],
  ["oldu", "happened/became/was/okay/done"],
  ["istiyorum", "I want/I would like"],
  ["onun", "his/her/its"],
  ["geri", "back/backward/rear"],
  ["bile", "even"],
  ["eğer", "if"],
  ["artık", "now/anymore/no longer/from now on/any longer/leftover"],
  ["gerçekten", "really/truly/indeed"],
  ["kim", "who"],
  ["bay", "Mr/mister/sir/gentleman"],
  ["yani", "so/I mean/that is/well/namely"],
  ["çünkü", "because/since"],
  ["büyük", "big/large/great/huge/elder"],
  ["doğru", "true/right/correct/straight/towards/truth"],
  ["peki", "okay/alright/well/so/ok"],
  ["buraya", "here/to here"],
  ["biliyorum", "I know"],
  ["başka", "another/other/else/different"],
  ["belki", "maybe/perhaps"],
  ["olarak", "as/being"],
  ["tanrım", "my god/god/oh my god"],
  ["tek", "only/single/one/sole/alone"],
  ["efendim", "sir/madam/pardon/yes/excuse me"],
  ["biri", "someone/somebody/one of/one"],
  ["olur", "okay/possible/it is possible/it happens/becomes/all right"],
  ["olacak", "will be/going to be/will happen"],
  ["adam", "man/guy/person"],
  ["haydi", "come on/let's/go on"],
  ["olan", "the one which/which is/that is/who is/being/happening/what happened"],
  ["İşte", "here/here it is/there/that's it/well/look"],
  ["et", "meat/flesh/do"],
  ["sanırım", "I think/I suppose/I guess"],
  ["merhaba", "hello/hi"],
  ["biz", "we/us"],
  ["orada", "there/over there"],
  ["demek", "to say/to mean/means/so"],
  ["teşekkürler", "thanks/thank you"],
  ["hiçbir", "no/none/any/not any"],
  ["nerede", "where"],
  ["yardım", "help/aid/assistance"],
  ["ederim", "I do/I make/thanks"],
  ["bilmiyorum", "I don't know/I do not know"],
  ["gün", "day"],
  ["gece", "night/at night"],
  ["fazla", "more/too much/too/excess/extra"],
  ["bütün", "all/whole/entire/complete"],
  ["bunun", "of this/this/this one's"],
  ["tüm", "all/whole/entire"],
  ["harika", "wonderful/great/amazing/excellent/fantastic/awesome"],
  ["ile", "with/and/by"],
  ["yeni", "new"],
  ["gel", "come"],
  ["biliyor", "he knows/she knows/knows/knowing"],
  ["iki", "two"],
  ["kötü", "bad/evil/poor"],
  ["küçük", "small/little/tiny/young"],
  ["tam", "full/complete/exactly/whole/just/right"],
  ["olsun", "let it be/so be it/whatever/fine"],
  ["siz", "you"],
  ["son", "last/final/end/latest"],
  ["şeyler", "things/stuff"],
  ["ol", "be/become"],
  ["bayan", "woman/lady/miss/madam/Mrs/Ms"],
  ["şeyi", "thing/the thing"],
  ["hemen", "immediately/right away/at once/now/soon"],
  ["size", "you/to you/for you"],
  ["sorun", "problem/issue/trouble/ask"],
  ["üzgünüm", "I'm sorry/sorry/I am sad"],
  ["ver", "give"],
  ["onları", "them"],
  ["lanet", "curse/damn/damned/cursed"],
  ["teşekkür", "thanks/thank you"],
  ["devam", "continue/continuation/go on/keep going"],
  ["kız", "girl/daughter"],
  ["git", "go/leave/go away"],
  ["sizi", "you"],
  ["dostum", "my friend/buddy/dude/man/pal"],
  ["gerek", "necessary/need/needed/must"],
  ["pekala", "ok/okay/alright/all right/fine/very well"],
  ["bizi", "us"],
  ["bize", "to us/us/for us"],
  ["hakkında", "about/concerning/regarding"],
  ["buna", "to this/this/at this"],
  ["kendi", "own/self/oneself"],
  ["baba", "father/dad/daddy"],
  ["aynı", "same"],
  ["anne", "mother/mom/mum/mommy"],
  ["dur", "stop/wait/halt/stand"],
  ["oluyor", "is happening/happens/becomes/is going on"],
  ["mısın", "are you"],
  ["iş", "work/job/business/task"],
  ["kimse", "nobody/no one/noone/anyone/anybody"],
  ["asla", "never"],
  ["diye", "saying/so that/as/called/that"],
  ["izin", "permission/leave/allow/vacation"],
  ["hala", "still/aunt"],
  ["seninle", "with you"],
  ["şunu", "this/that"],
  ["olabilir", "it could be/may be/maybe/possible/could be/might be"],
  ["mü", "question particle/is it"],
  ["söyle", "say/tell/say it/tell me"],
  ["benimle", "with me"],
  ["tabii", "of course/sure/certainly/naturally"],
  ["para", "money"],
  ["bizim", "our/ours"],
  ["selam", "hi/hello/greetings/salute"],
  ["yoksa", "or/otherwise/or else/if not"],
  ["içinde", "inside/in/within"],
  ["önemli", "important"],
  ["değilim", "I am not/I'm not"],
  ["yüzden", "therefore/so/that's why/because of"],
  ["herkes", "everyone/everybody/all"],
  ["ister", "wants/whether"],
  ["gidelim", "let's go"],
  ["dakika", "minute"],
  ["bırak", "leave/let go/drop/quit/stop"],
  ["geldi", "came/arrived/has come"],
  ["üç", "three"],
  ["biliyorsun", "you know"],
  ["işte", "here/here it is/there/that's it/well/look"],
  ["tekrar", "again/repeat"],
  ["vardı", "there was/there were/had"],
  ["bakalım", "let's see"],
  ["istiyorsun", "you want"],
  ["onlar", "they/them"],
  ["bugün", "today"],
  ["özür", "apology/sorry/excuse"],
  ["buradan", "from here/this way"],
  ["hep", "always/all"],
  ["miyim", "am I"],
  ["yine", "again/still/anyway"],
  ["yapıyorsun", "you are doing/you do/you are making"],
  ["bekle", "wait/hold on"],
  ["uzun", "long/tall"],
  ["gerçek", "real/true/truth/reality/actual"],
  ["geliyor", "coming/is coming/comes"],
  ["saat", "hour/clock/watch/time/o'clock"],
  ["aslında", "actually/in fact/really"],
  ["olmak", "to be/to become/to happen"],
  ["çocuklar", "children/kids/guys"],
  ["neler", "what/what things"],
  ["nedir", "what is/what is it"],
  ["çocuk", "child/kid/boy"],
  ["bence", "I think/in my opinion/according to me"],
  ["burası", "here/this place"],
  ["onunla", "with him/with her/with it"],
  ["eve", "home/to the house/house"],
  ["ilk", "first/initial"],
  ["göre", "according to/by/for"],
  ["sizin", "your/yours"],
  ["yer", "place/ground/floor/eats/space/location"],
  ["nereye", "where/to where/where to"],
  ["birlikte", "together/with"],
  ["yıl", "year"],
  ["hepsi", "all/all of them/everything"],
  ["kaç", "how many/how much/run/escape/flee"],
  ["dinle", "listen"],
  ["şekilde", "in a way/way/like/in the way/manner"],
  ["olmaz", "impossible/no way/no/it won't do/can't be"],
  ["pek", "much/very/not very/hardly/quite"],
  ["yere", "to the ground/to the floor/to a place/ground"],
  ["tanrı", "god"],
  ["istemiyorum", "I don't want/I do not want"],
  ["emin", "sure/certain/safe/secure"],
  ["fakat", "but/however"],
  ["hazır", "ready/prepared"],
  ["zaten", "already/anyway"],
  ["birkaç", "a few/several/some"],
  ["dilerim", "I wish/I hope"],
  ["söz", "promise/word/saying"],
  ["söyledi", "said/told/he said/she said"],
  ["lazım", "required/necessary/needed/need"],
  ["kendini", "yourself/himself/herself/oneself/self"],
  ["olmalı", "should be/must be/must"],
  ["tane", "unit/piece/item/one"],
  ["etmek", "to do/to make"],
  ["misiniz", "are you"],
  ["ediyorum", "I am doing/I do"],
  ["seviyorum", "I love/I like"],
  ["tatlım", "sweetie/honey/sweetheart/darling"],
  ["bunlar", "these/they"],
  ["karşı", "opposite/against/across/towards"],
  ["kesinlikle", "definitely/absolutely/certainly/exactly"],
  ["görmek", "to see"],
  ["birşey", "something/anything"],
  ["yarın", "tomorrow"],
  ["olduğu", "that is/is/being/which is/where"],
  ["benden", "from me/than me"],
  ["elbette", "certainly/of course/sure"],
  ["istiyor", "wants/he wants/she wants"],
  ["aman", "oh/oh my/mercy/please"],
  ["az", "little/few/less/a little"],
  ["eski", "old/former/ancient/ex"],
  ["edin", "do/get/make"],
  ["anda", "at the moment/moment/instant/at/at once"],
  ["kadın", "woman/lady"],
  ["İki", "two"],
  ["kahretsin", "damn it/damn/dammit"],
  ["işi", "work/job/his job/business"],
  ["yapmak", "to do/to make"],
  ["ilgili", "relating to/related/about/interested/concerning"],
  ["an", "moment/instant"],
  ["oraya", "there/to there"],
  ["onlara", "them/to them"],
  ["dikkat", "attention/caution/care/careful/watch out"],
  ["gerekiyor", "it is necessary/necessary/needs/must/have to"],
  ["dışarı", "outside/out"],
  ["diğer", "other/another"],
  ["yapma", "don't do that/don't/stop it/doing/making"],
  ["işe", "to work/to the job/work"],
  ["hoş", "pleasant/nice/lovely"],
  ["bundan", "from this/of this/about this"],
  ["zor", "difficult/hard/tough"],
  ["kez", "times/time"],
  ["sakin", "calm/quiet/beware"],
  ["mutlu", "happy"],
  ["bakın", "look"],
  ["geç", "late/pass/go"],
  ["kabul", "acceptance/accept/agree/admission"],
  ["senden", "from you/than you"],
  ["dedim", "I said/I told"],
  ["çabuk", "quick/quickly/fast/hurry"],
  ["gidip", "going/go and"],
  ["niye", "why"],
  ["yemek", "food/meal/dinner/to eat"],
  ["hafta", "week"],
  ["yerde", "on the ground/on the floor/somewhere"],
  ["kişi", "person/people"],
  ["musunuz", "are you"],
  ["zorunda", "have to/must/obliged/forced"],
  ["yanlış", "wrong/false/mistake/incorrect"],
  ["görüşürüz", "see you later/see you/bye"],
  ["özel", "special/private/personal"],
  ["gördüm", "I saw/I have seen"],
  ["gidiyor", "going/is going/leaves"],
  ["doktor", "doctor/physician"],
  ["ediyor", "is doing/does/makes"],
  ["bazı", "some/certain"],
  ["kes", "cut/stop/shut up"],
  ["yalnız", "only/alone/lonely/but"],
  ["hem", "both/also/and"],
  ["babam", "my father/my dad"],
  ["beş", "five"],
  ["gitti", "gone/went/left"],
  ["polis", "police/cop/policeman"],
  ["erkek", "male/man/boy"],
  ["merak", "curiosity/wonder/worry/curious"],
  ["nereden", "from where/where from/how"],
  ["kontrol", "control/check"],
  ["insan", "person/human/people/human being"],
  ["birini", "someone/somebody/one"],
  ["eminim", "I am sure/I'm sure"],
  ["ondan", "from him/from her/from it/than him/that's why"],
  ["insanlar", "people/humans"],
  ["aptal", "stupid/fool/idiot/silly"],
  ["gereken", "required/necessary/needed"],
  ["falan", "like/so and so/or something/etc/and so on"],
  ["sağ", "right/alive"],
  ["ihtiyacım", "I need/my need"],
  ["etti", "did/made"],
  ["gördün", "you saw/you have seen"],
  ["dolar", "dollar/dollars"],
  ["umarım", "I hope"],
  ["beri", "since"],
  ["değildi", "wasn't/was not"],
  ["etme", "do not/don't"],
  ["öldü", "died/dead/is dead"],
  ["nefret", "hate/hatred"],
  ["veya", "or"],
  ["sanki", "as if/as though/like"],
  ["yeter", "enough/that's enough"],
  ["su", "water"],
  ["adamım", "my man/man/buddy/dude"],
  ["yap", "do/make"],
  ["kendine", "yourself/to yourself/himself/herself"],
  ["haber", "news/message"],
  ["sabah", "morning"],
  ["kendimi", "myself"],
  ["dün", "yesterday"],
  ["akşam", "evening/tonight"],
  ["ateş", "fire/fever/shoot"],
  ["yalan", "lie/false"],
  ["dört", "four"],
  ["geçen", "last/past/passing"],
  ["kal", "stay/remain"],
  ["sonunda", "finally/at last/in the end/at the end"],
  ["annem", "my mother/my mom"],
  ["dünya", "world/earth"],
  ["sence", "in your opinion/do you think/you think"],
  ["değilsin", "you are not/you're not"],
  ["ay", "month/moon/oh"],
  ["yaptım", "I did/I made"],
  ["yerine", "instead/instead of/in its place/in place of"],
  ["hangi", "which/what"],
  ["istediğim", "what I want/I want/that I want"],
  ["bunları", "these/them"],
  ["boyunca", "along/throughout/during/for"],
  ["üzerinde", "on/on top of/over/above"],
  ["tamamen", "completely/totally/entirely"],
  ["adı", "name/his name/her name/its name"],
  ["tabi", "of course/sure/subject to"],
  ["karar", "decision"],
  ["vardır", "there are/there is/there must be"],
  ["aç", "hungry/open"],
  ["olduğumu", "that I am/I am"],
  ["adım", "my name/step"],
  ["olun", "be"],
  ["gitmek", "to go/to leave"],
  ["dedi", "he said/she said/said"],
  ["ayrıca", "moreover/also/besides/in addition"],
  ["bitti", "finished/over/done/ended"],
  ["gelecek", "future/coming/next/will come"],
  ["sakın", "beware/don't/never"],
  ["genç", "young/youth/young person"],
  ["öyleyse", "then/so/in that case"],
  ["olmuş", "happened/been/become/has been"],
  ["bende", "me too/on me/with me/I have"],
  ["farklı", "different"],
  ["yaptın", "you did/you made"],
  ["olamaz", "can't be/impossible/no way/cannot be"],
  ["bazen", "sometimes"],
  ["açık", "open/clear/light/on"],
  ["bebeğim", "my baby/baby"],
  ["yol", "path/road/way"],
  ["pekâlâ", "ok/okay/alright/all right/very well"],
  ["söyledim", "I said/I told"],
  ["dr", "Dr./doctor"],
  ["olursa", "if/if it is/if it happens"],
  ["İlk", "first/initial"],
  ["oldukça", "quite/rather/fairly/pretty/increasingly"],
  ["zamanı", "time/time to/its time"],
  ["tarafından", "by"],
  ["sahip", "owner/have/master"],
  ["içeri", "inside/in"],
  ["neyse", "anyway/whatever/never mind"],
  ["alo", "hello"],
  ["oldum", "I became/I have been/I was"],
  ["beraber", "together/with"],
  ["mükemmel", "perfect/excellent"],
  ["onların", "their/theirs"],
  ["bilirsin", "you know"],
  ["eder", "does/makes/costs"],
  ["ettim", "I did/I made"],
  ["oğlum", "my son/son/boy"],
  ["cevap", "reply/answer/response"],
  ["henüz", "yet/just/not yet"],
  ["on", "ten"],
  ["yapıyor", "is doing/does/is making"],
  ["ise", "if/whereas/as for"],
  ["herif", "guy/dude/fellow"],
  ["olması", "being/to be/its being"],
  ["aldım", "I bought/I took/I got"],
  ["konuşmak", "to talk/to speak"],
  ["uzak", "far/distant/away"],
  ["kolay", "easy"],
  ["yanında", "next to/beside/with/near/next to you"],
  ["evde", "at home/in the house"],
  ["adamı", "man/the man/guy"],
  ["birisi", "someone/somebody"],
  ["evlat", "son/child/kid"],
  ["başına", "per/to his head/to its head/on your own/to the head"],
  ["fark", "difference/notice"],
  ["hayatım", "my life/my love/darling/honey"],
  ["saniye", "second"],
  ["acele", "rush/hurry/haste"],
  ["araba", "car"],
  ["düşünüyorsun", "you think/you are thinking"],
  ["çocuğu", "child/the child/his child/the kid"],
  ["geldim", "I came/I am here/I'm here/I'm coming/I have come"],
  ["yoktu", "there was none/there wasn't/did not have/wasn't"],
  ["olsa", "if/even if/were"],
  ["rahat", "comfortable/easy/relaxed/at ease"],
  ["gidiyorum", "I am going/I'm going/I'm leaving"],
  ["hâlâ", "still"],
  ["yolu", "way/road/the way/the road/path"],
  ["görünüyor", "it appears/seems/looks/appears"],
  ["ara", "search/call/look for/break/interval/between"],
  ["yüzünden", "because/because of/due to"],
  ["dersin", "you say/lesson/what do you say"],
  ["neredeyse", "almost/nearly"],
  ["ancak", "however/but/only"],
  ["hızlı", "fast/quick/quickly"],
  ["dans", "dance"],
  ["günü", "day/the day"],
  ["halde", "in/although/in case/in the state/while"],
  ["savaş", "war/battle/fight"],
  ["söylemek", "to say/to tell"],
  ["çeneni", "your chin/your mouth/your jaw"],
  ["ev", "house/home"],
  ["geceler", "nights"],
  ["almak", "to take/to buy/to get/to receive"],
  ["şuna", "to this/to that/at this/at that"],
  ["altında", "under/below/beneath"],
  ["vay", "wow"],
  ["olmadığını", "that it is not/that he is not/that not/not being"],
  ["nasılsın", "how are you"],
  ["güle", "smile/goodbye/bye"],
  ["hepimiz", "all of us/we all"],
  ["sanmıyorum", "I don't think so/I don't think"],
  ["oyun", "game/play"],
  ["boş", "empty/blank/free/vacant"],
  ["süre", "duration/time/period"],
  ["bin", "thousand/get on/ride"],
  ["anlıyorum", "I understand/I see"],
  ["komik", "comic/funny"],
  ["durum", "situation/status/condition/state"],
  ["galiba", "probably/I guess/I think/apparently"],
  ["yaptı", "did/made/he did/she did"],
  ["hava", "weather/air"],
  ["kaldı", "remained/stayed/left/is left"],
  ["duydum", "I heard"],
  ["günaydın", "good morning"],
  ["yeniden", "again/anew"],
  ["kapıyı", "door/the door"],
  ["buldum", "I found"],
  ["miyiz", "are we"],
  ["takip", "follow-up/follow/tracking"],
  ["olacağım", "I will be/I'll be"],
  ["gelin", "bride/come/daughter-in-law"],
  ["hayal", "dream/imagination/fantasy"],
  ["düşündüm", "I thought/I think"],
  ["sende", "you/on you/with you/you too/you have"],
  ["gidiyoruz", "we are going/we're going/we're leaving"],
  ["bebek", "baby/doll"],
  ["hayat", "life"],
  ["söylüyor", "says/is saying/tells"],
  ["ciddi", "serious/seriously"],
  ["yardımcı", "helper/assistant/helpful/deputy"],
  ["kapa", "close/shut/shut up"],
  ["altı", "six/under/bottom"],
  ["istedim", "I wanted/I asked"],
  ["işin", "your job/your work/the work/the job"],
  ["canım", "darling/my dear/dear/honey/my life"],
  ["konuda", "on the subject/about/on the issue/in the matter"],
  ["göz", "eye"],
  ["adamın", "man's/the man's"],
  ["beyler", "gentlemen/guys"],
  ["düşünüyorum", "I am thinking/I think/I'm thinking"],
  ["gidiyorsun", "you are leaving/you are going"],
  ["yaşlı", "old/elderly"],
  ["çalışıyorum", "I am working/I'm working/I'm trying/I work"],
  ["herhangi", "any/anyone"],
  ["azından", "at least"],
  ["böylece", "thus/so/in this way/like this"],
  ["kardeşim", "my brother/my sister/my sibling/brother/bro"],
  ["beyaz", "white"],
  ["başladı", "started/began"],
  ["şaka", "joke/kidding"],
  ["gelip", "coming/come and"],
  ["telefon", "telephone/phone/call"],
  ["hareket", "movement/move/motion/action"],
  ["verin", "give"],
  ["gelen", "incoming/coming/who comes/the one who came"],
  ["sürü", "herd/flock/lots/bunch"],
  ["durun", "wait/stop"],
  ["üzerine", "on/over/on top of/about/onto"],
  ["gelir", "income/comes/will come"],
  ["memnun", "pleased/glad/happy/satisfied"],
  ["şeyin", "thing/of the thing/thing's"],
  ["kesin", "definite/certain/sure/exact/cut"],
  ["yolunda", "on the way/fine/okay/in order/on its way"],
  ["baban", "your father/your dad"],
  ["yeterince", "enough/sufficiently"],
  ["herşey", "everything"],
  ["hayatta", "alive/in life/never"],
  ["arada", "in between/between/sometimes/meanwhile"],
  ["arkadaşım", "my friend/friend"],
  ["kimin", "whose/who's"],
  ["güçlü", "strong/powerful"],
  ["el", "hand/stranger"],
  ["mısınız", "are you"],
  ["anladın", "you understood/got it/understand/do you understand"],
  ["verdi", "gave/he gave/she gave"],
  ["yakın", "close/near/nearby"],
  ["çıkar", "interest/benefit/take off/get out/comes out"],
  ["konusunda", "about/on/regarding/on the subject of"],
  ["garip", "strange/weird/odd"],
  ["bırakın", "leave/let go/drop"],
  ["hepsini", "all/all of them/everything"],
  ["şeye", "to the thing/to something/thing"],
  ["İçeri", "inside/in"],
  ["sanıyorsun", "you think/you suppose"],
  ["soru", "question"],
  ["silah", "weapon/gun"],
  ["parayı", "money/the money"],
  ["çıktı", "output/came out/went out/printout"],
  ["otur", "sit down/sit"],
  ["kısa", "short/brief"],
  ["yapacağım", "I will do/I will do it/I'll do"],
  ["çık", "exit/get out/go out"],
  ["geldin", "you came/you're here"],
  ["çalışıyor", "it works/works/is working/is trying"],
  ["korkunç", "terrible/horrible/awful"],
  ["durumda", "in case/in the situation/in a state/in condition"],
  ["anladım", "I understand/I understood/I see/got it"],
  ["acaba", "I wonder"],
  ["kızı", "daughter/the girl/his daughter/her daughter"],
  ["iyiyim", "I am good/I'm fine/I'm good/I am fine/I'm okay"],
  ["sağol", "thanks/thank you"],
  ["hatta", "even/in fact/actually"],
  ["uygun", "suitable/appropriate/fit/available"],
  ["haklısın", "you are right/you're right"],
  ["yapamam", "I can't do it/I can't/I cannot"],
  ["terk", "abandon/leave/desert"],
  ["yaptığını", "what you did/what he did/that you did"],
  ["siktir", "fuck/fuck off"],
  ["tür", "type/kind/species/sort/genre"],
  ["değildir", "is not/isn't"],
  ["olduğuna", "that/that it is"],
  ["geliyorum", "I am coming/I'm coming"],
  ["dön", "come back/return/turn/turn around"],
  ["şeyleri", "things"],
  ["kere", "times/time"],
  ["şöyle", "like this/this way/so"],
  ["dikkatli", "careful/carefully"],
  ["kan", "blood"],
  ["ait", "belonging/belongs/belonging to/of"],
  ["arasında", "between/among"],
  ["frank", "franc"],
  ["bilmek", "to know"],
  ["neyin", "what/of what"],
  ["neyi", "what"],
  ["aşağı", "down/below/downstairs"],
  ["çek", "pull/check/cheque/draw/Czech"],
  ["rahatsız", "uncomfortable/disturbed/bothered/disturb"],
  ["veriyorum", "I am giving/I give"],
  ["dünyanın", "world/world's/of the world"],
  ["dolu", "full/filled/loaded"],
  ["geçti", "passed/went by/over"],
  ["ortaya", "to emerge/out/to the middle"],
  ["verdim", "I gave"],
  ["varsa", "if/if there is/if any"],
  ["muhtemelen", "probably/likely"],
  ["yakında", "soon/nearby"],
  ["burda", "here"],
  ["sevindim", "I am pleased/I'm glad/glad/I am glad"],
  ["ihtiyacı", "need/needs/his need"],
  ["olacağını", "that it will be/that/will be"],
  ["neydi", "what was it/what was"],
  ["annen", "your mother/your mom"],
  ["diyorsun", "you say/you are saying"],
  ["sürekli", "continually/constantly/always/continuous"],
  ["milyon", "million"],
  ["yüksek", "high/tall/loud"],
  ["tuhaf", "strange/weird/odd"],
  ["sizinle", "with you"],
  ["hissediyorum", "I feel"],
  ["fikir", "idea/opinion"],
  ["zamanda", "in time/at the time/time"],
  ["deli", "crazy/mad/insane"],
  ["olmadan", "without/before"],
  ["dışında", "outside/except/apart from"],
  ["bizimle", "with us"],
  ["kahrolası", "goddamn/damn/damned"],
  ["at", "horse/throw"],
  ["başkan", "president/chairman/mayor/minister"],
  ["yukarı", "up/above/upstairs"],
  ["olmayacak", "will not happen/won't be/will not be"],
  ["bayım", "sir/mister"],
  ["acı", "pain/bitter/spicy/hot/suffering"],
  ["aldı", "took/bought/got"],
  ["olmadı", "it didn't happen/didn't work/wasn't"],
  ["dedin", "you said"],
  ["aşk", "love"],
  ["olası", "possible/probable/likely"],
  ["yalnızca", "just/only/merely"],
  ["getir", "bring"],
  ["biliyordum", "I knew"],
  ["kızlar", "girls"],
  ["sensin", "it's you/you are"],
  ["tatlı", "sweet/dessert/cute"],
  ["hoşça", "nicely/pleasantly"],
  ["affedersiniz", "excuse me/sorry/pardon"],
  ["ediyorsun", "you are doing/you do"],
  ["yemin", "oath/swear/vow"],
  ["etmeye", "to do/to make"],
  ["ölüm", "death"],
  ["ölü", "dead"],
  ["içine", "into/inside"],
  ["yapacağız", "we will/we will do/we'll do"],
  ["edecek", "will/will do"],
  ["dışarıda", "outside/out"],
  ["üzere", "on/about to/in order to/as"],
  ["yavaş", "slow/slowly"],
  ["tut", "hold/keep/catch"],
  ["ihtiyacın", "your need/you need"],
  ["tahmin", "guess/estimate/prediction"],
  ["herşeyi", "everything"],
  ["koca", "husband/huge/big"],
  ["birinin", "someone's/somebody's"],
  ["sessiz", "silent/quiet"],
  ["hasta", "sick/ill/patient"],
  ["gizli", "hidden/secret"],
  ["mümkün", "possible"],
  ["yapacak", "will do/going to do"],
  ["duydun", "you heard"],
  ["olurdu", "would be/would have been"],
  ["köpek", "dog"],
  ["amerika", "America"],
  ["yapıyorum", "I am doing/I'm doing/I do"],
  ["gerektiğini", "that it is necessary/that/should"],
  ["ihtiyacımız", "our need/we need"],
  ["berbat", "terrible/awful/wretched/lousy"],
  ["istersen", "if you want/if you like"],
  ["zarar", "damage/harm/loss"],
  ["sıcak", "hot/warm"],
  ["ana", "main/mother/primary"],
  ["şans", "chance/luck"],
  ["gidin", "go/leave"],
  ["sanıyordum", "I thought"],
  ["oradan", "from there"],
  ["kahve", "coffee"],
  ["yapmaya", "to do/to make"],
  ["yapar", "does/makes/would do"],
  ["olay", "event/incident/case"],
  ["dek", "until"],
  ["görünüyorsun", "you look/you seem/you appear"],
  ["diyor", "says/is saying"],
  ["şarkı", "song"],
  ["vermek", "to give"],
  ["kalk", "get up/stand up"],
  ["nefes", "breath"],
  ["olup", "being/happening"],
  ["anlaşıldı", "understood/got it/roger"],
  ["sevgili", "beloved/darling/dear/girlfriend/boyfriend/lover"],
  ["görüyorum", "I see"],
  ["orospu", "bitch/whore"],
  ["bilmem", "I don't know"],
  ["üstüne", "over/on/on top of/onto"],
  ["insanların", "people/people's"],
  ["evine", "to your home/home/to his home"],
  ["varmış", "there was/apparently there is"],
  ["İnsanlar", "people"],
  ["basit", "simple/easy"],
  ["istediğini", "what you want/what he wants"],
  ["pislik", "dirt/scum/bastard/mess"],
  ["kızım", "my daughter/my girl/girl"],
  ["zavallı", "poor/miserable/pathetic"],
  ["istedi", "wanted/asked"],
  ["olmayan", "non/not/which is not/nonexistent"],
  ["yedi", "seven/ate"],
  ["alın", "forehead/take"],
  ["tıpkı", "just as/just like/exactly like"],
  ["olmalısın", "you must be/you should be"],
  ["yıldır", "for years/years"],
  ["isterim", "I would like/I want"],
  ["buradayım", "I am here/I'm here"],
  ["birine", "to someone/someone/to one"],
  ["herkesin", "everyone/everyone's"],
  ["keşke", "if only/I wish"],
  ["dalga", "wave"],
  ["benziyor", "it looks like/looks like/resembles"],
  ["zamandır", "for/for a long time/since"],
  ["sesini", "your voice/his voice/the sound/voice"],
  ["unutma", "don't forget"],
  ["neye", "what/at what/to what"],
  ["sefer", "time/times/expedition/trip"],
  ["aldın", "you bought/you took/you got"],
  ["bilmiyor", "he doesn't know/doesn't know/she doesn't know"],
  ["diyorum", "I say/I'm saying"],
  ["çeviri", "translation"],
  ["ufak", "small/little/tiny"],
  ["herhalde", "probably/I guess"],
  ["ahbap", "buddy/pal/dude/friend"],
  ["bununla", "with this"],
  ["baş", "head/chief"],
  ["ettin", "you did/you made"],
  ["yapacaksın", "you will do"],
  ["yeterli", "sufficient/enough"],
  ["muhteşem", "wonderful/magnificent/gorgeous/amazing"],
  ["yüz", "face/hundred/swim"],
  ["olacaksın", "you will be"],
  ["çekil", "withdraw/move/get out of the way/step aside"],
  ["görüyor", "sees"],
  ["yeri", "place/the place/its place"],
  ["aşkına", "for the love of/for your love"],
  ["önünde", "in front/in front of/ahead"],
  ["söyledin", "you said/you told"],
  ["belli", "clear/obvious/certain/evident"],
  ["söylüyorum", "I'm saying/I am saying/I say/I'm telling"],
  ["miydi", "was it"],
  ["hata", "mistake/error/fault"],
  ["söylemiştim", "I told you/I had said"],
  ["aile", "family"],
  ["fena", "bad"],
  ["düşün", "think"],
  ["bunların", "these/of these"],
  ["alabilir", "can take/may take/can get/can buy"],
  ["numara", "number/trick"],
  ["evi", "house/the house/home"],
  ["bayanlar", "ladies"],
  ["tehlikeli", "dangerous"],
  ["millet", "people/nation/folks"],
  ["alıp", "taking/take and"],
  ["bilir", "knows"],
  ["yaşında", "age/years old/aged"],
  ["doğum", "birth"],
  ["yürü", "walk"],
  ["yoktur", "there is none/there isn't/there is no"],
  ["bekliyor", "waiting/is waiting/waits"],
  ["inanamıyorum", "I can't believe it/I can't believe"],
  ["gitmem", "I'm leaving/I won't go/my going"],
  ["adına", "on behalf of/in the name of/in his name"],
  ["birçok", "a lot/many/a lot of"],
  ["ses", "sound/voice/noise"],
  ["içki", "drink/alcohol/booze"],
  ["erken", "early"],
  ["hayatını", "your life/life/his life"],
  ["bok", "shit"],
  ["kendisi", "itself/himself/herself"],
  ["vakit", "time"],
  ["İsa", "Jesus"],
  ["adını", "name/your name/his name"],
  ["ele", "hand/to hand/to the hand"],
  ["seks", "sex"],
  ["sıkı", "tight/strict/firm"],
  ["anlıyor", "understands"],
  ["yaparım", "I will do it/I do/I'll do"],
  ["edeceğim", "I will/I will do"],
  ["aynen", "exactly/just like"],
  ["güvenlik", "security/safety"],
  ["canlı", "live/alive/lively"],
  ["müzik", "music"],
  ["kaptan", "captain"],
  ["hatırlıyor", "remembers"],
  ["güç", "strength/power/force/difficult"],
  ["sonraki", "next/following"],
  ["saçma", "nonsense/ridiculous/absurd"],
  ["kimsin", "who are you"],
  ["kırmızı", "red"],
  ["günler", "days"],
  ["söyleme", "don't say/don't tell/saying"],
  ["anlamıyorum", "I don't understand"],
  ["aşık", "in love/lover"],
  ["arkadaş", "friend"],
  ["verir", "gives"],
  ["bekleyin", "wait"],
  ["durumu", "situation/the situation/condition/status"],
  ["bakma", "don't look/look"],
  ["kimsenin", "nobody/nobody's/anybody's"],
  ["arkadaşın", "your friend"],
  ["temiz", "clean"],
  ["oda", "room"],
  ["birşeyler", "something/some things"],
  ["niçin", "why"],
  ["geldik", "we arrived/we came/we're here"],
  ["çocukları", "children/the children/kids"],
  ["olduğum", "I am/that I am"],
  ["düşünüyor", "thinks/is thinking"],
  ["olduğun", "you are/that you are"],
  ["olsaydı", "if/if it were/if there were"],
  ["olmasını", "to be/being"],
  ["e", "well/so/eh"],
  ["bilemiyorum", "I don't know/I can't know"],
  ["konuşma", "speech/talk/conversation/don't talk"],
  ["buldun", "you found"],
  ["istediğin", "what you want/you want"],
  ["mıydı", "was it"],
  ["ikinci", "second"],
  ["noel", "Christmas"],
  ["parti", "party"],
  ["zamanlar", "times"],
  ["baksana", "look/hey"],
  ["yapmam", "I won't do it/I won't/my doing"],
  ["işler", "works/things/business/jobs"],
  ["üstünde", "above/on/on top of/over"],
  ["sonsuza", "forever/to eternity"],
  ["yerinde", "in place/in your place/appropriate/on the spot"],
  ["anlat", "explain/tell/to explain"],
  ["insanları", "people"],
  ["sayın", "dear/respected/honorable"],
  ["gelmiş", "has arrived/has come/came"],
  ["sıra", "order/turn/row/line/queue"],
  ["bilmiyordum", "I didn't know"],
  ["asıl", "real/actual/main/original"],
  ["kızın", "girl/girl's/your daughter/your girl"],
  ["seviyor", "loves/likes"],
  ["soğuk", "cold"],
  ["siyah", "black"],
  ["yapalım", "let's do it/let's do"],
  ["işim", "my job/my work/my business"],
  ["birden", "suddenly/at once/all of a sudden"],
  ["almaya", "to buy/to take/to get"],
  ["in", "get down/get off/come down/descend"],
  ["yanına", "next to/beside/with/near"],
  ["göster", "show"],
  ["patron", "boss"],
  ["alacağım", "I will take/I will buy/I will get"],
  ["buradaki", "here/the one here"],
  ["sonu", "end/the end"],
  ["tarafa", "side/way/to the side"],
  ["sigara", "cigarette"],
  ["salak", "idiot/stupid/fool"],
  ["gerekir", "is necessary/must/should/needs"],
  ["bahsediyorsun", "you are talking about"],
  ["olmasın", "not/let it not be/don't be"],
  ["haklı", "right/justified"],
  ["sert", "hard/tough/harsh"],
  ["konu", "subject/topic/issue/matter"],
  ["burayı", "here/this place"],
  ["olmaya", "to be/to become"],
  ["defa", "times/time"],
  ["umurumda", "I care"],
  ["hak", "right/justice/deserve"],
  ["özellikle", "especially/particularly"],
  ["biliyoruz", "we know"],
  ["bulmak", "to find"],
  ["kimseye", "to nobody/to anyone/anyone"],
  ["baylar", "gentlemen"],
  ["gitsin", "let him go/let it go/go"],
  ["adamlar", "men/guys"],
  ["yemeği", "food/the food/meal/dinner"],
  ["tercih", "preference/prefer/choice"],
  ["İyiyim", "I am good/I'm fine/I'm good/I am fine/I'm okay"],
  ["istiyorsan", "if you want"],
  ["dinleyin", "listen"],
  ["geldiniz", "you have arrived/you came"],
  ["olma", "being/don't be"],
  ["iyisi", "the best/better/the good one"],
  ["bilgi", "information/knowledge/info"],
  ["işini", "your job/your work/his job"],
  ["acil", "urgent/emergency"],
  ["kalın", "thick/stay"],
  ["arabayı", "car/the car"],
  ["dair", "about/concerning/regarding"],
  ["yapabilirim", "I can/I can do"],
  ["biriyle", "with someone/with somebody"],
  ["hepiniz", "all of you/you all"],
  ["öldürmek", "to kill/kill"],
  ["söylüyorsun", "you say/you're saying/you are saying"],
  ["alır", "takes/buys/gets"],
  ["İşe", "to work/to the job/work"],
  ["defol", "get out/go away/get lost"],
  ["gerçeği", "the truth/truth/real"],
  ["bağlı", "connected/tied/dependent/depends"],
  ["babası", "father/his father/her father"],
  ["duyuyor", "hears"],
  ["babamın", "my father's/my dad's"],
  ["yola", "on the road/to the road/on the way"],
  ["onlarla", "with them"],
  ["görmedim", "I didn't see/I haven't seen"],
  ["amerikan", "American"],
  ["gayet", "very/quite"],
  ["rağmen", "despite/although/in spite of"],
  ["onlardan", "from them/of them"],
  ["anlamı", "meaning"],
  ["istemiyor", "doesn't want/does not want"],
  ["tanıyor", "he knows/knows/recognizes"],
  ["şehir", "city/town"],
  ["zorundayım", "I have to/I must"],
  ["dua", "prayer/pray"],
  ["değiliz", "we are not/we're not"],
  ["yaşıyor", "he is alive/lives/is living/alive"],
  ["hoşçakal", "goodbye/bye"],
  ["çoğu", "most"],
  ["taraftan", "from/on the other hand/side"],
  ["kitap", "book"],
  ["orası", "that place/there"],
  ["yerini", "place/your place/its place"],
  ["söyleyeyim", "let me tell you/let me say"],
  ["gelmek", "to come"],
  ["adın", "your name"],
  ["bizden", "from us/than us"],
  ["bakayım", "let me see/let me look"],
  ["uyuşturucu", "drugs/drug/narcotic"],
  ["kalan", "remainder/remaining/rest/left"],
  ["dolayı", "because/because of/due to"],
  ["görmeye", "to see"],
  ["kendime", "to myself/myself"],
  ["teslim", "delivery/surrender/submit/deliver"],
  ["güneş", "sun"],
  ["kusura", "sorry/excuse/fault"],
  ["kral", "king"],
  ["kapı", "door/gate"],
  ["zengin", "rich/wealthy"],
  ["parçası", "part/piece/part of"],
  ["edebilir", "can/can do/may"],
  ["gir", "enter/come in/get in"],
  ["dürüst", "honest"],
  ["kendim", "myself"],
  ["iç", "drink/inside/inner"],
  ["kadınlar", "women"],
  ["cehenneme", "to hell"],
  ["kalmak", "to stay/to remain"],
  ["kapat", "close/shut/turn off/hang up"],
  ["altın", "gold/golden"],
  ["silahı", "gun/the gun/weapon"],
  ["okul", "school"],
  ["çalışıyorsun", "you are working/you work/you're trying"],
  ["gider", "expense/goes/leaves"],
  ["canına", "to your soul/your life"],
  ["yüzbaşı", "captain"],
  ["affedersin", "excuse me/sorry/pardon"],
  ["istiyorsunuz", "you want"],
  ["şeyden", "from/from the thing/than anything"],
  ["sık", "often/frequent/dense/tight/squeeze"],
  ["gurur", "pride/proud"],
  ["vereceğim", "I will give"],
  ["mesaj", "message"],
  ["istiyoruz", "we want"],
  ["sekiz", "eight"],
  ["hoşuma", "I like it/I like"],
  ["yaptığı", "what he did/what she did/what it did"],
  ["eğlenceli", "fun/entertaining"],
  ["ağır", "heavy/slow/serious"],
  ["takım", "team/set/suit"],
  ["karım", "my wife"],
  ["davet", "invitation/invite"],
  ["kutsal", "sacred/holy"],
  ["ölmüş", "dead/died/has died"],
  ["yıllar", "years"],
  ["yarım", "half/my lover"],
  ["yapan", "the one who/doing/maker/who did"],
  ["hanımefendi", "lady/madam/ma'am"],
  ["konuş", "talk/speak"],
  ["ray", "rail"],
  ["saçmalık", "nonsense/bullshit/absurdity"],
  ["sona", "end/to the end"],
  ["olduğundan", "because/since/than it is"],
  ["herkese", "to everyone/everyone"],
  ["güvenli", "safe/secure/trustworthy"],
  ["getirdim", "I brought it/I brought"],
  ["sahibi", "owner"],
  ["fikrim", "my opinion/my idea"],
  ["çekilin", "move aside/step aside/get out of the way"],
  ["dünyada", "in the world"],
  ["satın", "buy/purchase"],
  ["bira", "beer"],
  ["gitmeliyim", "I have to go/I must go/I should go"],
  ["teklif", "offer/proposal"],
  ["altına", "under/below"],
  ["aferin", "well done/good job/bravo"],
  ["gidecek", "will go/will leave"],
  ["aptalca", "stupid/foolish/stupidly"],
  ["bul", "find"],
  ["mavi", "blue"],
  ["demektir", "means"],
  ["hatırlıyorum", "I remember"],
  ["yüce", "sublime/supreme/great/almighty"],
  ["koy", "put/bay"],
  ["yaptığın", "what you did/what you do"],
  ["unut", "forget"],
  ["suç", "crime/fault/guilt/offense"],
  ["elinde", "in his hand/in your hand/in hand/in the hands of/in her hand"],
  ["balık", "fish"],
  ["şuraya", "over there/there/to there"],
  ["severim", "I like/I love"],
  ["sebep", "reason/cause"],
  ["parça", "piece/part/song/track"],
  ["yapıyorsunuz", "you are doing/you do"],
  ["arka", "back/rear/behind"],
  ["arkadaşı", "friend/his friend/her friend"],
  ["elini", "hand/your hand/his hand"],
  ["eskiden", "before/formerly/in the past/used to"],
  ["verici", "transmitter/giver/donor"],
  ["katil", "killer/murderer"],
  ["peder", "father/priest"],
  ["kelime", "word"],
  ["isterdim", "I would have liked to/I would like/I wish"],
  ["düşünüyordum", "I was thinking"],
  ["deniz", "sea"],
  ["günün", "of the day/day/your day"],
  ["çocuğun", "child/child's/your child"],
  ["pis", "filthy/dirty"],
  ["istemedim", "I didn't want"],
  ["hoşuna", "you like/like/like it"],
  ["gitme", "don't go/don't leave/going"],
  ["adama", "to the man/man"],
  ["sene", "year"],
  ["istemem", "I don't want"],
  ["götür", "take/carry"],
  ["akşamlar", "evenings/good evening"],
  ["cinayet", "murder/homicide"],
  ["İş", "work/job/business/task"],
  ["ayağa", "to the foot/up/on your feet/stand up"],
  ["ellerini", "hands/your hands"],
  ["mesela", "for example/for instance"],
  ["anlaşma", "agreement/deal/contract"],
  ["kimseyi", "nobody/anybody/anyone"],
  ["alan", "area/field/the one who takes/buyer"],
  ["yaz", "summer/write"],
  ["gerekiyordu", "it was necessary/had to/should have"],
  ["ilginç", "interesting"],
  ["kavga", "fight/quarrel/brawl"],
  ["iyilik", "goodness/favor/kindness"],
  ["serbest", "free/loose"],
  ["söyler", "says/tells"],
  ["edelim", "let's/let's do"],
  ["geldiğini", "that he came/that you came/coming"],
  ["sevgilim", "my love/darling/sweetheart/my lover/honey"],
  ["resmi", "official/formal/picture/the picture"],
  ["arabaya", "to the car/in the car/car"],
  ["olacağız", "we will be"],
  ["biliyorsunuz", "you know"],
  ["afedersiniz", "excuse me/sorry/pardon"],
  ["veriyor", "gives/is giving"],
  ["oldun", "you became/you have been"],
  ["san", "fame/reputation/title/singing"],
  ["söyleyeceğim", "I will tell/I will say"],
  ["yaklaşık", "approximately/about/around"],
  ["öğrenmek", "to learn/to find out"],
  ["yazık", "what a pity/pity/shame/too bad"],
  ["üçüncü", "third"],
  ["buralarda", "around here"],
  ["kayıp", "loss/lost/missing"],
  ["tebrikler", "congratulations"],
  ["kendin", "yourself"],
  ["sizden", "from you/than you"],
  ["hikaye", "story/tale"],
  ["çoktan", "already/long ago"],
  ["başıma", "to my head/to me/on my head"],
  ["kaldım", "I stayed/I remained/I was left"],
  ["erkekler", "men/boys"],
  ["söyleyin", "tell/say"],
  ["telefonu", "phone/the phone"],
  ["hale", "halo/state/condition"],
  ["albay", "colonel"],
  ["birinci", "first"],
  ["yapmayı", "to do/doing"],
  ["birazdan", "soon/in a moment/shortly"],
  ["duymak", "to hear/to listen"],
  ["gideceğim", "I'm going/I will go/I'll go"],
  ["olanlar", "those/what happened/the ones/events"],
  ["endişelenme", "don't worry"],
  ["çeşit", "sort/kind/type/variety"],
  ["edeyim", "I'll do it/let me"],
  ["isim", "name/noun"],
  ["gittim", "I went"],
  ["duyuyorum", "I hear"],
  ["yapabilir", "can/can do/may do"],
  ["yaptığım", "what I did/what I do"],
  ["müthiş", "wonderful/awesome/terrific/amazing"],
  ["piç", "bastard"],
  ["ifade", "expression/statement/testimony"],
  ["sesi", "voice/sound/his voice/the sound"],
  ["sebebi", "reason/the reason/cause"],
  ["şimdiye", "now/so far/until now"],
  ["şef", "chef/chief/boss"],
  ["zeki", "intelligent/smart/clever"],
  ["düşünmüştüm", "I thought/I had thought"],
  ["süper", "super/great"],
  ["hayatın", "life/your life/of life"],
  ["kalmadı", "no more/none left/nothing left"],
  ["vakti", "time"],
  ["birileri", "someone/somebody/some people"],
  ["dan", "from"],
  ["görünüşe", "appearance/apparently"],
  ["mıyım", "am I"],
  ["yaşamak", "to live/to be alive"],
  ["şanslı", "lucky"],
  ["derece", "degree"],
  ["geriye", "back/backwards"],
  ["okula", "to school/school"],
  ["tanıyorum", "I know/I recognize"],
  ["herkesi", "everyone/everybody"],
  ["alıyorum", "I am getting/I am taking/I am buying/I take"],
  ["karanlık", "darkness/dark"],
  ["kimi", "who/whom/some"],
  ["yada", "or"],
  ["yapmış", "did/has done/made"],
  ["sırada", "next/in line/in turn/at the moment"],
  ["verme", "giving/don't give"],
  ["gerekli", "necessary/required/needed"],
  ["saygı", "respect"],
  ["koş", "run"],
  ["hayatımı", "my life"],
  ["orda", "there"],
  ["yiyecek", "food/will eat"],
  ["olmayı", "to be/being"],
  ["yaşam", "life"],
  ["çıkıp", "going out/getting out"],
  ["kalacak", "will stay/will remain"],
  ["kadının", "woman's/of the woman"],
  ["vur", "hit/shoot/strike"],
  ["sol", "left"],
  ["iyidir", "it is good/good/fine"],
  ["gördüğüm", "I saw/that I saw/I've seen"],
  ["dene", "try"],
  ["farkında", "aware"],
  ["gördünüz", "you saw"],
  ["evin", "house/your house/the house's"],
  ["yapmadım", "I didn't/I didn't do"],
  ["alıyor", "is taking/takes/is buying"],
  ["asker", "soldier"],
  ["olurum", "I will be/I'd be"],
  ["hayatı", "life/his life/her life"],
  ["isteyen", "wanting/who wants/whoever wants"],
  ["yaramaz", "naughty/useless/no good"],
  ["bulduk", "we found"],
  ["yoldan", "from the road/out of the way/off the road"],
  ["yapıyoruz", "we are doing/we do"],
  ["suçlu", "guilty/criminal"],
  ["neredesin", "where are you"],
  ["nesi", "what/what's wrong with"],
  ["çift", "couple/pair/double"],
  ["korkarım", "I'm afraid/I am afraid"],
  ["görev", "duty/task/mission"],
  ["tarafta", "on the side/side"],
  ["kara", "black/land"],
  ["döndü", "turned/returned/came back"],
  ["nerde", "where"],
  ["inanılmaz", "unbelievable/incredible/amazing"],
  ["çavuş", "sergeant"],
  ["verdin", "you gave"],
  ["yapabilirsin", "you can do/you can"],
  ["gözlerini", "eyes/your eyes"],
  ["nedeni", "reason/the reason/cause"],
  ["İkinci", "second"],
  ["bilmiyorsun", "you don't know"],
  ["güven", "trust/confidence"],
  ["üst", "top/upper/above"],
  ["polisi", "police/the police/policeman"],
  ["annesi", "mother/his mother/her mother"],
  ["sürece", "as long as/process"],
  ["arıyorum", "I am searching/I'm looking for/I'm calling"],
  ["hayvan", "animal"],
  ["oyunu", "game/the game/play"],
  ["etmez", "does not/doesn't"],
  ["hediye", "gift/present"],
  ["dünyayı", "world/the world"],
  ["istersin", "you want/you would like"],
  ["açın", "open"],
  ["istediğimi", "what I want"],
  ["giden", "outgoing/going/leaving"],
  ["daima", "always"],
  ["mal", "goods/property"],
  ["ayak", "foot/leg"],
  ["zorundasın", "you have to/you must"],
  ["duruyor", "it is standing/stands/stops/stays"],
  ["olayı", "the event/event/incident"],
  ["cidden", "really/seriously"],
  ["kadını", "woman/the woman"],
  ["ciddiyim", "I am serious/I'm serious"],
  ["olman", "being/you being/your being"],
  ["öldürdü", "he killed/killed"],
  ["sever", "loves/likes"],
  ["uyan", "wake up"],
  ["profesör", "professor"],
  ["sevdim", "I loved it/I liked it/I liked"],
  ["kalsın", "let it stay/keep it"],
  ["elde", "in hand/obtain"],
  ["sıradan", "ordinary/common"],
  ["nasılsınız", "how are you"],
  ["şanslar", "chances"],
  ["çalıştım", "I worked/I tried/I studied"],
  ["olabilirim", "I might be/I could be"],
  ["çalışan", "worker/employee/working"],
  ["alman", "German"],
  ["kalp", "heart"],
  ["söylemiştin", "you said/you had said/you told"],
  ["iğrenç", "disgusting"],
  ["yanımda", "next to me/with me/beside me"],
  ["sarhoş", "drunk"],
  ["haline", "into/state/condition"],
  ["tamamdır", "ok/okay/alright/done"],
  ["verecek", "will give"],
  ["alacak", "will receive/will take/will buy/receivable"],
  ["çıkmak", "to leave/to go out/to exit/to date"],
  ["yolda", "on the road/on the way"],
  ["tutun", "hold on/hold/tobacco"],
  ["ediyoruz", "we are/we are doing/we do"],
  ["ortak", "partner/common/shared"],
  ["kafa", "head/mind"],
  ["ön", "front"],
  ["edersin", "you do/you make"],
  ["kaldır", "remove/lift/raise"],
  ["londra", "London"],
  ["sahi", "really/actually/seriously"],
  ["anlamına", "meaning/means"],
  ["amca", "uncle"],
  ["baştan", "from the beginning/from the start/again"],
  ["istiyorlar", "they want"],
  ["teğmen", "lieutenant"],
  ["gibiydi", "it was like/seemed"],
  ["dedektif", "detective"],
  ["korkuyorum", "I am scared/I'm afraid/I am afraid"],
  ["rica", "request/please/you're welcome"],
  ["dava", "case/lawsuit/cause"],
  ["işleri", "jobs/work/things/business"],
  ["kulak", "ear"],
  ["gücü", "power/strength"],
  ["gitmiş", "gone/went/has gone"],
  ["gerekecek", "will be required/will need/will have to"],
  ["veririm", "I will give/I give"],
  ["arıyor", "looking/calling/is looking for/is calling"],
  ["muydu", "was it"],
  ["geldiğinde", "when/when he comes/when you come"],
  ["olduğumuzu", "that we are"],
  ["güzeldi", "it was beautiful/it was nice/it was good"],
  ["mektup", "letter"],
  ["günde", "daily/a day/per day/in a day"],
  ["ders", "lesson/class"],
  ["annemin", "my mother's/my mom's"],
  ["yoluna", "on the way/your way/its way"],
  ["çay", "tea"],
  ["muyum", "am I"],
  ["yerden", "from the ground/from the floor"],
  ["derin", "deep"],
  ["etmiş", "done/did/made"],
  ["türlü", "various/kind/sort of"],
  ["yaptık", "we did/we made"],
  ["yolunu", "the way/your way/its way"],
  ["akıllı", "clever/smart/intelligent/wise"],
  ["değer", "value/worth/worth it"],
  ["ettiğini", "that he did/what you did/that you did"],
  ["getirin", "bring it/bring"],
  ["oturun", "sit down/sit"],
  ["etmeyin", "don't"],
  ["domuz", "pig"],
  ["çalış", "work/study/try"],
  ["özgür", "free"],
  ["önceden", "previously/beforehand/in advance"],
  ["kapalı", "closed/shut/off"],
  ["şeytan", "devil/satan"],
  ["yardıma", "help/to help"],
  ["güney", "south"],
  ["önemi", "importance"],
  ["sürpriz", "surprise"],
  ["kişisel", "personal"],
  ["grup", "group"],
  ["alayım", "I'll take it/let me take/I'll have"],
  ["miydin", "were you"],
  ["başlıyor", "it starts/starts/is starting/begins"],
  ["uçak", "aeroplane/airplane/plane/aircraft"],
  ["sorunun", "the problem/your problem/the question"],
  ["evli", "married"],
  ["dünyaya", "to the world/into the world"],
  ["alırım", "I'll take it/I'll take/I'll have"],
  ["ortadan", "from the middle/out of sight/away"],
  ["istediği", "what he wanted/what she wants/what he wants"],
  ["ikiniz", "the two of you/you two/both of you"],
  ["doğal", "natural"],
  ["buydu", "this was it/that was it"],
  ["bekliyorum", "I am waiting/I'm waiting/I expect"],
  ["bildiğim", "I know/that I know"],
  ["bazıları", "some/some of them"],
  ["konuşuyor", "speaking/talking/is talking"],
  ["hani", "you know/where/remember"],
  ["kaza", "accident"],
  ["majesteleri", "your majesty/his majesty/her majesty"],
  ["ilgisi", "interest/relation"],
  ["insanlara", "to people/people"],
  ["ziyaret", "visit"],
  ["diğerleri", "others/the others"],
  ["elimden", "from my hand/I can"],
  ["İnsan", "person/human/people/human being"],
  ["başladım", "I started/I began"],
  ["yeşil", "green"],
  ["çocukların", "children/children's"],
  ["ikna", "persuasion/convince/persuade"],
  ["babanın", "your father's/your father"],
  ["yarısı", "half"],
  ["rüya", "dream"],
  ["kat", "floor/story/layer/fold"],
  ["arkasında", "behind"],
  ["edildi", "was done/was made"],
  ["hiçbirşey", "nothing/anything"],
  ["topu", "ball/the ball"],
  ["kuzey", "north"],
  ["muydun", "were you"],
  ["top", "ball/cannon"],
  ["bey", "gentleman/Mr/sir"],
  ["buradasın", "you are here/you're here"],
  ["bahse", "bet/I bet"],
  ["etmeyi", "to do/doing"],
  ["sonuna", "to the end/end"],
  ["ölmek", "to die"],
  ["can", "life/soul/dear"],
  ["şurada", "there/over there"],
  ["adamla", "with the man/with the guy"],
  ["almış", "received/took/bought/has taken"],
  ["aşağıda", "below/downstairs/down"],
  ["degil", "not/is not"],
  ["değerli", "valuable/precious"],
  ["ararım", "I'll call/I will call"],
  ["zorundayız", "we have to/we must"],
  ["kafayı", "mind/head"],
  ["numaralı", "numbered/number"],
  ["olduğunuzu", "that you are/that you"],
  ["zamanlarda", "in times/at times"],
  ["ileri", "forward/ahead/advanced"],
  ["önceki", "former/previous/prior"],
  ["başarılı", "successful"],
  ["yapman", "do/you do/your doing"],
  ["gerekirse", "if necessary/if needed"],
  ["zevk", "pleasure/taste/fun"],
  ["destek", "support/backup"],
  ["olabilirsin", "you could be/you might be"],
  ["gelmiyor", "not coming/doesn't come/isn't coming"],
  ["geçiyor", "it's passing/passing/passes"],
  ["seksi", "sexy"],
  ["ajan", "agent"],
  ["aradı", "called/searched"],
  ["oğlu", "son/his son/her son"],
  ["inanıyorum", "I believe"],
  ["olduklarını", "that they are/that"],
  ["dışı", "outside/exterior/outer"],
  ["sorunu", "problem/the problem"],
  ["şeker", "sugar/candy/sweet/diabetes"],
  ["gitmeliyiz", "we must go/we have to go/we should go"],
  ["aşağıya", "down/downstairs"],
  ["çıkıyor", "it is coming out/comes out/is going out/is dating"],
  ["kardeş", "brother/sister/sibling"],
  ["derhal", "immediately/at once"],
  ["olmam", "I am/my being/I won't be"],
  ["mıyız", "are we"],
  ["dokuz", "nine"],
  ["iyiydi", "it was good/it was nice"],
  ["mesele", "issue/matter/problem/question"],
  ["gelmedi", "did not come/didn't come"],
  ["don", "frost/underwear/pants"],
  ["yatak", "bed"],
  ["kalmış", "remained/left/stayed"],
  ["olmadığı", "not/that it is not"],
  ["insanın", "human/human's/one's"],
  ["çin", "Chinese/China"],
  ["dönmek", "to return/to turn/to come back"],
  ["roma", "Rome"],
  ["konuyu", "the subject/subject/the topic"],
  ["oturup", "sit/sitting"],
  ["geleni", "the one who comes/whoever comes"],
  ["resim", "picture/painting/image/photo"],
  ["İmdat", "help"],
  ["gelebilir", "can come/may come"],
  ["arıyorsun", "you are looking for/you are calling"],
  ["yazıyor", "writes/is writing/it says"],
  ["yabancı", "foreign/foreigner/stranger"],
  ["şarap", "wine"],
  ["kaybettim", "I lost"],
  ["kıçını", "your ass/ass"],
  ["çalışma", "study/work/working/don't work"],
  ["ünlü", "famous"],
  ["bomba", "bomb"],
  ["nasıi", "how"],
  ["üzgün", "sad/sorry"],
  ["olanları", "those/what happened"],
  ["olduğunda", "when/when it is"],
  ["askeri", "military/soldier"],
  ["imkansız", "impossible"],
  ["tehdit", "threat/threatening"],
  ["araya", "inter/in between/between"],
  ["yemeğe", "to dinner/to eat/for dinner"],
  ["elimde", "in my hand/I have"],
  ["alt", "lower/bottom/below/under"],
  ["deme", "don't say"],
  ["olanı", "the/the one/what happened"],
  ["çalışmak", "to work/to study/to try"],
  ["adamları", "men/his men"],
  ["çılgın", "crazy/mad"],
  ["yağmur", "rain"],
  ["anlamadım", "I don't understand/I didn't understand"],
  ["etrafta", "around"],
  ["boktan", "shitty/crappy"],
  ["aşağılık", "vile/despicable/contemptible"],
  ["buz", "ice"],
  ["güvende", "safe"],
  ["hapse", "to prison/to jail"],
  ["gideceğiz", "we will go"],
  ["çekici", "attractive/charming/tow truck/hammer"],
  ["sanmıştım", "I thought"],
  ["havaya", "into the air/air"],
  ["yakışıklı", "handsome"],
  ["İzin", "permission/leave/allow/vacation"],
  ["aklıma", "to my mind/my mind"],
  ["yıldız", "star"],
  ["mantıklı", "logical/reasonable"],
  ["girdi", "entry/entered/input/went in"],
  ["sevdiğim", "I love/that I love/my favorite"],
  ["sandım", "I thought"],
  ["aklını", "mind/your mind"],
  ["demiştim", "I said/I told you/I had said"],
  ["ailem", "my family"],
  ["buyurun", "please come in/here you are/please/go ahead"],
  ["İngiliz", "English/British/Englishman"],
  ["edebilirim", "I can"],
  ["kocaman", "huge/enormous"],
  ["söylemem", "I won't tell/I won't say"],
  ["ailesi", "family/his family/her family"],
  ["kime", "to who/to whom/who"],
  ["öldür", "kill"],
  ["olsam", "if I were"],
  ["ederiz", "we do/thank you"],
  ["teki", "one/one of"],
  ["evden", "from home/from the house"],
  ["konuşabilir", "can speak/can talk"],
  ["çıkın", "exit/get out"],
  ["şerif", "sheriff"],
  ["kardeşin", "your brother/your sister/your sibling"],
  ["başlıyoruz", "we're starting/we are starting"],
  ["söylediler", "they said/they told"],
  ["düştü", "fell/fell down/dropped"],
  ["mr", "Mr./mister"],
  ["geçmiş", "past/history"],
  ["sor", "ask"],
  ["hazırım", "I am ready/I'm ready"],
  ["başla", "start/begin"],
  ["dokunma", "don't touch/touch/touching"],
  ["şimdilik", "for now/for the time being"],
  ["evinde", "at home/at his home/in your house"],
  ["aşırı", "extreme/excessive/too much/over"],
  ["aramızda", "among us/between us"],
  ["değildim", "I wasn't/I was not"],
  ["söyleyecek", "to say/will say/will tell"],
  ["karısı", "wife/his wife"],
  ["bunlardan", "from these/of these"],
  ["hatırladın", "you remembered"],
  ["sayılmaz", "does not count/doesn't count"],
  ["memur", "officer/official/civil servant/clerk"],
  ["yan", "side/next"],
  ["dünyadaki", "in the world"],
  ["gittiğini", "that he went/that you went/that he left"],
  ["oynamak", "to play/play"],
  ["yüzünü", "face/your face"],
  ["yapayım", "I'll do it/let me do"],
  ["öylece", "just like that/just"],
  ["kitabı", "book/the book"],
  ["girin", "enter/come in"],
  ["birer", "one each"],
  ["aldık", "we bought/we took/we got"],
  ["zayıf", "weak/thin/skinny"],
  ["sıkıcı", "boring"],
  ["bayağı", "pretty/quite/rather/vulgar"],
  ["işten", "from work"],
  ["saatte", "per hour/an hour/at o'clock/in an hour"],
  ["adil", "fair/just"],
  ["önüne", "before/in front of"],
  ["söylemişti", "he said/had said/she said/he had told"],
  ["çirkin", "ugly"],
  ["ışık", "light"],
  ["uzakta", "away/far away/far"],
  ["zamanında", "on time/in time/in its time"],
  ["pazar", "Sunday/market/bazaar"],
  ["anlama", "understanding/meaning/don't understand"],
  ["geleceğim", "I will come/I'll come/my future"],
  ["söylemedim", "I didn't say/I didn't tell"],
  ["ikimiz", "the two of us/both of us/we two"],
  ["kenara", "aside/to the side"],
  ["not", "note/notes/grade"],
  ["İnanılmaz", "unbelievable/incredible/amazing"],
  ["kuş", "bird"],
  ["yana", "side/to the side"],
  ["savaşı", "war/the war/battle"],
  ["hizmet", "service"],
  ["yaşayan", "live/living/who lives"],
  ["lan", "damn/man/dude/hey"],
  ["sahte", "fake/false/counterfeit"],
  ["yapın", "do/make"],
  ["polisler", "police officers/policemen/cops/police"],
  ["başlayalım", "let's begin/let's start"],
  ["ruh", "soul/spirit/ghost"],
  ["olacaktır", "will be"],
  ["gemi", "boat/ship"],
  ["buldu", "found"],
  ["söylemeye", "to say/to tell"],
  ["söylediğim", "what I said"],
  ["sınıf", "class/classroom/grade"],
  ["başı", "head/his head/beginning"],
  ["evlilik", "marriage"],
  ["çıkarın", "remove/take off/take out"],
  ["anlaştık", "we agreed/deal/agreed"],
  ["bilim", "science"],
  ["işine", "to work/your business/to your job"],
  ["düzgün", "smooth/proper/neat/straight"],
  ["ismi", "name/his name/her name"],
  ["dönerim", "I'll return/I'll be back"],
  ["fazlasını", "more"],
  ["hayatımın", "my life/of my life"],
  ["binlerce", "thousands"],
  ["zenci", "black/negro"],
  ["genelde", "in general/usually/generally"],
  ["afedersin", "excuse me/sorry/pardon"],
  ["karın", "your wife/belly/stomach/snow/profit"],
  ["zamana", "time/to time"],
  ["gelince", "when/as for/when it comes"],
  ["gelmez", "will not come/doesn't come"],
  ["aradım", "I called/I searched"],
  ["gibisin", "you are like/you seem"],
  ["bişey", "something/anything"],
  ["korumak", "to protect/protect"],
  ["los", "Los"],
  ["ediyorlar", "they are/they are doing"],
  ["fransız", "French"],
  ["göstermek", "to show"],
  ["İngiltere", "England/Britain"],
  ["dahil", "including/included"],
  ["filmi", "movie/film/the movie"],
  ["oradaki", "there/over there"],
  ["hastaneye", "to the hospital"],
  ["iyice", "thoroughly/well"],
  ["konuşmaya", "to speak/to talk"],
  ["öldürmeye", "to kill"],
  ["tamir", "fix/repair"],
  ["avukat", "lawyer/attorney"],
  ["kocam", "my husband"],
  ["öldürdün", "you killed"],
  ["olursun", "you will be/you would be"],
  ["gösteriyor", "shows"],
  ["suyu", "water/juice"],
  ["hamile", "pregnant"],
  ["iptal", "cancel/cancellation"],
  ["yukarıda", "above/upstairs/up"],
  ["koç", "ram/coach/Aries"],
  ["iyisini", "the best/better"],
  ["bol", "plenty/loose/abundant"],
  ["prenses", "princess"],
  ["cuma", "Friday"],
  ["yargıç", "judge"],
  ["cesur", "brave/courageous"],
  ["mil", "mile/shaft"],
  ["döneceğim", "I'll be back/I will return"],
  ["diyeceğim", "I will say"],
  ["parasını", "his money/money/your money"],
  ["param", "my money"],
  ["taş", "stone/rock"],
  ["hallederim", "I'll handle it/I'll take care of it"],
  ["kadarıyla", "as far as"],
  ["bıraktım", "I left/I quit/I dropped"],
  ["bakmak", "to look/to take care"],
  ["meşgul", "busy/occupied"],
  ["odasında", "in his room/in her room/in the room"],
  ["yaptığımı", "what I did"],
  ["ettik", "we did/we made"],
  ["etmem", "I won't/I don't"],
  ["nerden", "from where/where from"],
  ["süredir", "for a long time/for/since"],
  ["mutluyum", "I am happy/I'm happy"],
  ["boşver", "nevermind/never mind/forget it"],
  ["doğu", "east"],
  ["yapacağımı", "what I will do"],
  ["getirdi", "brought"],
  ["görüyorsun", "you see"],
  ["canını", "your life/your soul"],
  ["yaparsın", "you can do it/you do/you would do"],
  ["hangisi", "which one/which"],
  ["yapamazsın", "you can't/you cannot"],
  ["fırsat", "opportunity/chance"],
  ["zamanki", "time/at the time"],
  ["kedi", "cat"],
  ["birazcık", "a little/a bit"],
  ["sağlam", "durable/solid/strong/sound"],
  ["şansı", "chance/luck"],
  ["başkanı", "president/chairman"],
  ["zamandan", "from time/time"],
  ["taksi", "taxi"],
  ["batı", "west"],
  ["sizce", "in your opinion/do you think"],
  ["olmuştu", "it had happened/had been/had become"],
  ["kör", "blind"],
  ["girmek", "to enter/to get in"],
  ["haberi", "news/the news"],
  ["göremiyorum", "I can't see"],
  ["unuttum", "I forgot"],
  ["yakaladım", "I caught it/I caught/got it"],
  ["vahşi", "wild/savage"],
  ["özledim", "I miss/I missed"],
  ["söylerim", "I'll tell you/I'll tell/I say"],
  ["hayatımda", "in my life"],
  ["görmüş", "seen/saw"],
  ["elimizde", "in our hands/we have"],
  ["bıraktı", "left/quit/dropped"],
  ["hatırlamıyorum", "I can't remember/I don't remember"],
  ["değiller", "they are not/they aren't"],
  ["gösteri", "show/demonstration/performance"],
  ["birbirimizi", "each other"],
  ["yolculuk", "journey/trip/travel"],
  ["arkadaşlar", "friends/guys"],
  ["yahudi", "Jewish/Jew"],
  ["İşin", "your job/your work/the work/the job"],
  ["durma", "don't stop/stop"],
  ["hayir", "no"],
  ["söylesene", "tell me"],
  ["girecek", "will enter"],
  ["emir", "order/command"],
  ["yapabiliriz", "we can/we can do"],
  ["kulağa", "to the ear/sounds"],
  ["sırasında", "during"],
  ["diyelim", "let's say"],
  ["olmasına", "to be/although"],
  ["adi", "ordinary/vile/mean"],
  ["öğle", "noon/lunch"],
  ["kiminle", "with who/with whom"],
  ["babamı", "my father/my dad"],
  ["geride", "back/behind"],
  ["istedin", "you wanted/you asked"],
  ["silahını", "your weapon/your gun/gun"],
  ["yerlerde", "in places/on the floor"],
  ["dönüp", "turn/turning/come back"],
  ["elinden", "from your hand/from his hand"],
  ["kurtarmak", "to save/to rescue"],
  ["İnsanların", "people/people's"],
  ["nasıldı", "how was it"],
  ["fotoğraf", "photograph/photo/picture"],
  ["ters", "opposite/wrong/reverse/backwards"],
  ["bölüm", "section/chapter/episode/department/part"],
  ["budur", "this is it/that's it"],
  ["çıplak", "naked/nude"],
  ["tavuk", "chicken"],
  ["geçiyorsun", "you are passing/you're going through"],
  ["yarı", "half/semi"],
  ["of", "ugh/ouch"],
  ["benzer", "similar/alike/resembles"],
  ["başında", "at the beginning/at the head of/at"],
  ["buradayız", "we are here/we're here"],
  ["etmiyor", "does not/doesn't"],
  ["öldüreceğim", "I will kill"],
  ["İstediğin", "what you want/you want"],
  ["söylemedin", "you didn't say/you didn't tell"],
  ["veren", "giving/giver/who gives"],
  ["rapor", "report"],
  ["çıkmış", "out/came out/gone out"],
  ["ikisi", "the two/both/both of them"],
  ["bilirsiniz", "you know"],
  ["kahraman", "hero"],
  ["odası", "room/his room"],
  ["arama", "call/search/don't call"],
  ["şükür", "thanks/thank god"],
  ["olmuyor", "it isn't happening/it doesn't work/not working"],
  ["konusu", "subject/topic"],
  ["konuştum", "I spoke/I talked"],
  ["kaltak", "bitch"],
  ["fahişe", "whore/prostitute"],
  ["ayrı", "separate/apart"],
  ["giriş", "entrance/entry/login/introduction"],
  ["harekete", "movement/into action/action"],
  ["kullan", "use"],
  ["cesaret", "bravery/courage"],
  ["ettiler", "they did/they made"],
  ["adında", "named/called"],
  ["edemem", "I can't"],
  ["parlak", "shiny/bright/brilliant"],
  ["sayesinde", "thanks to"],
  ["alalım", "let's buy it/let's take/let's get"],
  ["yüzde", "percentage/percent/in the face"],
  ["işaret", "sign/signal/mark"],
  ["şeyim", "my thing/thing"],
  ["bakıyorum", "I'm looking/I am looking"],
  ["bizler", "we"],
  ["kızla", "with the girl"],
  ["İngilizce", "English"],
  ["bilirim", "I know"],
  ["merkezi", "central/center/headquarters"],
  ["konuşuyorsun", "you are talking/you are speaking"],
  ["masum", "innocent"],
  ["dediğimi", "what I said"],
  ["girerim", "I'll enter/I'll go in"],
  ["düşman", "enemy"],
  ["edeceğiz", "we will"],
  ["kişinin", "person/person's"],
  ["yirmi", "twenty"],
  ["sıradaki", "next"],
  ["yapmamı", "do/me to do"],
  ["birbirimize", "to each other"],
  ["görüşmek", "to meet/to see"],
  ["ettiğim", "I did/that I did"],
  ["başa", "to the beginning/to the start"],
  ["okulda", "at school"],
  ["bakıyorsun", "you are looking"],
  ["dönüyor", "it's spinning/returns/turns/is coming back"],
  ["çıkan", "out/coming out/outgoing"],
  ["beyefendi", "gentleman/sir"],
  ["gittin", "you left/you went"],
  ["kıza", "to the girl"],
  ["bölge", "area/region/zone"],
  ["orta", "middle/medium/center"],
  ["yat", "lie down/sleep/go to bed/yacht"],
  ["parmak", "finger"],
  ["futbol", "football/soccer"],
  ["filan", "etc/or something/and so on"],
  ["itibaren", "from/since/as of"],
  ["yapıyorlar", "they are doing"],
  ["ihtiyaç", "need"],
  ["araştırma", "research/investigation"],
  ["tedavi", "treatment/cure"],
  ["sorumlu", "responsible"],
  ["hariç", "not including/except/excluding"],
  ["cep", "pocket/mobile"],
  ["arasındaki", "between"],
  ["sus", "shush/be quiet/shut up"],
  ["ardından", "behind/after/afterwards"],
  ["birisin", "someone/you are someone"],
  ["engel", "obstacle/barrier"],
  ["ülke", "country"],
  ["şimdiden", "already/in advance"],
  ["tren", "train"],
  ["ortada", "in the middle/in the open"],
  ["geliyorlar", "they are coming"],
  ["idare", "administration/management/manage"],
  ["tarafı", "side"],
  ["fransa", "France"],
  ["serseri", "rascal/bum/punk"],
  ["nazik", "kind/polite/gentle"],
  ["bırakıp", "leave/leaving"],
  ["burdan", "from here"],
  ["istiyordum", "I wanted"],
  ["televizyon", "television/TV"],
  ["yıllık", "annual/yearly"],
  ["gene", "again"],
  ["olmaktan", "from/from being"],
  ["tanıştığımıza", "to meet/nice to meet you"],
  ["üzerinden", "over/through/from"],
  ["bulmaya", "to find"],
  ["seçim", "vote/election/choice"],
  ["iyisin", "you're good/you are good/you're fine"],
  ["madem", "since"],
  ["odada", "in the room"],
  ["kar", "snow/profit"],
  ["arabada", "in the car"],
  ["parası", "money/his money"],
  ["canavar", "monster/beast"],
  ["numarası", "number/his number"],
  ["konuşalım", "let's talk"],
  ["banka", "bank"],
  ["kurt", "wolf/Kurd/worm"],
  ["sakıncası", "disadvantage/objection/harm"],
  ["kızgın", "angry/mad"],
  ["annenin", "mother's/your mother's"],
  ["barış", "peace"],
  ["sormak", "to ask"],
  ["gördü", "saw"],
  ["verdiği", "gave/that he gave"],
  ["uyuyor", "sleeping/is sleeping"],
  ["yatağa", "to bed"],
  ["cumartesi", "Saturday"],
  ["kokuyor", "it smells/smells"],
  ["öğleden", "afternoon"],
  ["annemi", "my mother/my mom"],
  ["sey", "thing"],
  ["spor", "sport/sports"],
  ["nin", "of"],
  ["yalancı", "liar"],
  ["yolun", "the road/your way/the way"],
  ["hedef", "aim/target/goal"],
  ["avrupa", "Europe"],
  ["mutlaka", "definitely/certainly/surely/absolutely"],
  ["kazanmak", "to win/to earn"],
  ["onda", "in him/he has/at ten/in it"],
  ["İçinde", "inside/in/within"],
  ["polise", "to the police"],
  ["öldürecek", "will kill"],
  ["geleceğini", "your future/that he will come"],
  ["itiraf", "admission/confession/confess"],
  ["üstelik", "besides/moreover/furthermore"],
  ["savunma", "defense/defence"],
  ["odasına", "to his room/to her room"],
  ["gerekmiyor", "not needed/no need"],
  ["dönün", "turn/turn around/come back"],
  ["olağanüstü", "extraordinary/exceptional"],
  ["sevimli", "pleasant/cute/lovely"],
  ["dersiniz", "your lesson/you say"],
  ["usta", "expert/master"],
  ["epey", "quite/rather/a lot"],
  ["bilmiyoruz", "we don't know"],
  ["olabileceğini", "that it is possible/that it could be"],
  ["saldırı", "attack/assault"],
  ["yıllardır", "for years"],
  ["sola", "left/to the left"],
  ["neymiş", "what is it"],
  ["peşinde", "in pursuit/after/chasing"],
  ["yapmayın", "don't do it/don't"],
  ["demiştin", "you said"],
  ["olsaydım", "if I were/if I had been"],
  ["çıkış", "exit/output"],
  ["aşkım", "my love"],
  ["yapmamız", "what we do/we need to do"],
  ["vereyim", "I'll give"],
  ["yarar", "benefit/use"],
  ["bunda", "in this"],
  ["kendinizi", "yourself/yourselves"],
  ["öğrendim", "I learned/I found out"],
  ["hayatının", "of your life/your life"],
  ["tanışmak", "to meet"],
  ["biliyordu", "he knew/knew"],
  ["kimdi", "who was it/who was"],
  ["korku", "fear/horror"],
  ["veremem", "I can't give it/I can't give"],
  ["başını", "head/your head"],
  ["eğlence", "entertainment/fun"],
  ["yapacağını", "what you will do/what he will do"],
  ["bakmayın", "don't look"],
  ["derler", "they say"],
  ["unuttun", "you forgot"],
  ["hissettim", "I felt"],
  ["kısmı", "part/partial"],
  ["sanat", "art"],
  ["içeride", "inside/in"],
  ["doğrusu", "actually/to be honest/the truth"],
  ["İnan", "believe"],
  ["sır", "secret"],
  ["götürün", "take it/take"],
  ["inanmıyorum", "I don't believe"],
  ["tutmak", "to hold/to keep"],
  ["olmalıyım", "I must be/I should be"],
  ["amerikalı", "American"],
  ["kurşun", "lead/bullet"],
  ["üzüldüm", "I'm sorry/I'm sad"],
  ["diyorlar", "they say"],
  ["değilse", "otherwise/if not"],
  ["düğün", "wedding"],
  ["yasal", "legal"],
  ["ettiği", "he did/what he did"],
  ["fazlası", "more/excess"],
  ["kaçtı", "escaped/ran away/fled"],
  ["dediğim", "what I said"],
  ["bizde", "in us/we have/with us"],
  ["başından", "from the beginning/from the start"],
  ["sırf", "sheer/just/only/purely"],
  ["kendisini", "himself/herself/itself"],
  ["alma", "taking/don't take"],
  ["şeylerin", "things/of things"],
  ["ulusal", "national"],
  ["beyin", "brain"],
  ["etmelisin", "you should/you must"],
  ["fikrin", "your idea/your opinion"],
  ["kardeşi", "brother/sister/sibling"],
  ["edeceksin", "you will"],
  ["sürtük", "slut"],
  ["şansın", "chance/your chance/your luck"],
  ["insanı", "human/person/people"],
  ["istemiştim", "I wanted"],
  ["tavsiye", "recommendation/advice"],
  ["sağa", "right/to the right"],
  ["ordu", "army"],
  ["şerefe", "cheers"],
  ["canın", "your soul/your life/you"],
  ["çalışıyoruz", "we are working/we are trying"],

  // ---------- Part 2: everyday words ----------
  ["ekmek", "bread"],
  ["peynir", "cheese"],
  ["yumurta", "egg"],
  ["süt", "milk"],
  ["pirinç", "rice/brass"],
  ["makarna", "pasta"],
  ["çorba", "soup"],
  ["salata", "salad"],
  ["meyve", "fruit"],
  ["sebze", "vegetable"],
  ["elma", "apple"],
  ["muz", "banana"],
  ["portakal", "orange"],
  ["limon", "lemon"],
  ["çilek", "strawberry"],
  ["üzüm", "grape/grapes"],
  ["karpuz", "watermelon"],
  ["domates", "tomato"],
  ["patates", "potato"],
  ["soğan", "onion"],
  ["sarımsak", "garlic"],
  ["biber", "pepper"],
  ["havuç", "carrot"],
  ["tuz", "salt"],
  ["yağ", "oil/fat/butter"],
  ["bal", "honey"],
  ["zeytin", "olive"],
  ["öğle yemeği", "lunch"],
  ["akşam yemeği", "dinner/supper"],
  ["pasta", "cake"],
  ["kek", "cake/cupcake"],
  ["dondurma", "ice cream"],
  ["çikolata", "chocolate"],
  ["meyve suyu", "fruit juice/juice"],
  ["restoran", "restaurant"],
  ["kafe", "cafe/café"],
  ["garson", "waiter"],
  ["menü", "menu"],
  ["hesap", "bill/check/account/calculation"],
  ["bardak", "glass/cup"],
  ["fincan", "cup"],
  ["tabak", "plate"],
  ["çatal", "fork"],
  ["kaşık", "spoon"],
  ["bıçak", "knife"],
  ["şişe", "bottle"],
  ["mutfak", "kitchen"],
  ["lezzetli", "delicious/tasty"],
  ["acıkmak", "to get hungry/to be hungry"],
  ["susamak", "to get thirsty/to be thirsty"],
  ["pişirmek", "to cook/to bake"],
  ["yatak odası", "bedroom"],
  ["banyo", "bathroom/bath"],
  ["tuvalet", "toilet/restroom"],
  ["pencere", "window"],
  ["duvar", "wall"],
  ["masa", "table/desk"],
  ["sandalye", "chair"],
  ["koltuk", "armchair/seat/sofa"],
  ["dolap", "cupboard/wardrobe/closet"],
  ["buzdolabı", "fridge/refrigerator"],
  ["lamba", "lamp"],
  ["merdiven", "stairs/ladder"],
  ["anahtar", "key/switch"],
  ["bahçe", "garden/yard"],
  ["apartman", "apartment building/apartment"],
  ["komşu", "neighbor/neighbour"],
  ["kira", "rent"],
  ["ayna", "mirror"],
  ["sabun", "soap"],
  ["çanta", "bag/handbag"],
  ["gözlük", "glasses/eyeglasses"],
  ["şemsiye", "umbrella"],
  ["saç", "hair"],
  ["burun", "nose"],
  ["ağız", "mouth"],
  ["dil", "tongue/language"],
  ["boyun", "neck"],
  ["omuz", "shoulder"],
  ["kol", "arm/sleeve"],
  ["bacak", "leg"],
  ["sırt", "back"],
  ["mide", "stomach"],
  ["vücut", "body"],
  ["beden", "body/size"],
  ["baş ağrısı", "headache"],
  ["ağrı", "pain/ache"],
  ["grip", "flu"],
  ["ilaç", "medicine/drug"],
  ["eczane", "pharmacy/chemist"],
  ["hastane", "hospital"],
  ["hemşire", "nurse"],
  ["sağlık", "health"],
  ["sağlıklı", "healthy"],
  ["yorgun", "tired"],
  ["hastalık", "illness/disease/sickness"],
  ["iyileşmek", "to get better/to recover/to heal"],
  ["ağlamak", "to cry"],
  ["gülmek", "to laugh"],
  ["gülümsemek", "to smile"],
  ["uyumak", "to sleep"],
  ["uyanmak", "to wake up"],
  ["dinlenmek", "to rest"],
  ["yıkamak", "to wash"],
  ["giymek", "to wear/to put on"],
  ["çıkarmak", "to take off/to remove/to take out"],
  ["dede", "grandfather/grandpa"],
  ["büyükanne", "grandmother/grandma"],
  ["torun", "grandchild"],
  ["teyze", "aunt"],
  ["dayı", "uncle"],
  ["kuzen", "cousin"],
  ["yeğen", "nephew/niece"],
  ["abla", "older sister/big sister"],
  ["abi", "older brother/big brother"],
  ["eş", "spouse/wife/husband/partner"],
  ["nişanlı", "fiance/fiancee/engaged"],
  ["akraba", "relative/relatives"],
  ["erkek arkadaş", "boyfriend"],
  ["kız arkadaş", "girlfriend"],
  ["öğretmen", "teacher"],
  ["mühendis", "engineer"],
  ["işçi", "worker"],
  ["şoför", "driver/chauffeur"],
  ["pilot", "pilot"],
  ["aşçı", "cook/chef"],
  ["satıcı", "seller/salesman"],
  ["müdür", "manager/director/principal"],
  ["berber", "barber"],
  ["yazar", "writer/author"],
  ["şarkıcı", "singer"],
  ["oyuncu", "actor/actress/player"],
  ["emekli", "retired/pensioner"],
  ["işsiz", "unemployed/jobless"],
  ["meslek", "profession/occupation"],
  ["maaş", "salary/wage"],
  ["şirket", "company/firm"],
  ["ofis", "office"],
  ["toplantı", "meeting"],
  ["müşteri", "customer/client"],
  ["çalışkan", "hardworking/diligent"],
  ["tembel", "lazy"],
  ["ödev", "homework/assignment"],
  ["defter", "notebook"],
  ["kalem", "pen/pencil"],
  ["üniversite", "university"],
  ["öğretmek", "to teach"],
  ["okumak", "to read/to study"],
  ["yazmak", "to write"],
  ["anlamak", "to understand"],
  ["hatırlamak", "to remember"],
  ["unutmak", "to forget"],
  ["cevap vermek", "to answer/to reply"],
  ["sayı", "number"],
  ["cümle", "sentence"],
  ["sayfa", "page"],
  ["kütüphane", "library"],
  ["Türkçe", "Turkish"],
  ["köy", "village"],
  ["mahalle", "neighborhood/neighbourhood/district"],
  ["sokak", "street"],
  ["cadde", "avenue/street/road"],
  ["köprü", "bridge"],
  ["park", "park"],
  ["market", "market/supermarket/grocery store"],
  ["dükkan", "shop/store"],
  ["mağaza", "store/shop"],
  ["cami", "mosque"],
  ["kilise", "church"],
  ["müze", "museum"],
  ["sinema", "cinema/movie theater"],
  ["tiyatro", "theater/theatre"],
  ["otel", "hotel"],
  ["havalimanı", "airport"],
  ["istasyon", "station"],
  ["durak", "stop/bus stop"],
  ["plaj", "beach"],
  ["bina", "building"],
  ["adres", "address"],
  ["harita", "map"],
  ["otobüs", "bus"],
  ["bisiklet", "bicycle/bike"],
  ["metro", "subway/metro/underground"],
  ["bilet", "ticket"],
  ["pasaport", "passport"],
  ["tatil", "holiday/vacation"],
  ["seyahat", "travel/trip/journey"],
  ["gezmek", "to travel/to wander/to go around/to visit"],
  ["binmek", "to get on/to ride/to board"],
  ["inmek", "to get off/to go down/to land"],
  ["yürümek", "to walk"],
  ["koşmak", "to run"],
  ["uçmak", "to fly"],
  ["kaybolmak", "to get lost/to disappear"],
  ["düz", "straight/flat"],
  ["köşe", "corner"],
  ["doğa", "nature"],
  ["dağ", "mountain"],
  ["orman", "forest/woods"],
  ["ağaç", "tree"],
  ["çiçek", "flower"],
  ["nehir", "river"],
  ["göl", "lake"],
  ["ada", "island"],
  ["gökyüzü", "sky"],
  ["bulut", "cloud"],
  ["rüzgar", "wind"],
  ["fırtına", "storm"],
  ["güneşli", "sunny"],
  ["yağmurlu", "rainy"],
  ["serin", "cool"],
  ["mevsim", "season"],
  ["ilkbahar", "spring"],
  ["sonbahar", "autumn/fall"],
  ["kış", "winter"],
  ["inek", "cow"],
  ["koyun", "sheep"],
  ["tavşan", "rabbit"],
  ["aslan", "lion"],
  ["ayı", "bear"],
  ["fil", "elephant"],
  ["maymun", "monkey"],
  ["arı", "bee"],
  ["kelebek", "butterfly"],
  ["pazartesi", "Monday"],
  ["salı", "Tuesday"],
  ["çarşamba", "Wednesday"],
  ["perşembe", "Thursday"],
  ["ocak", "January/stove"],
  ["şubat", "February"],
  ["mart", "March"],
  ["nisan", "April"],
  ["mayıs", "May"],
  ["haziran", "June"],
  ["temmuz", "July"],
  ["ağustos", "August"],
  ["eylül", "September"],
  ["ekim", "October"],
  ["kasım", "November"],
  ["aralık", "December/gap/interval"],
  ["hafta sonu", "weekend"],
  ["öğleden sonra", "afternoon/in the afternoon"],
  ["gece yarısı", "midnight"],
  ["geçen hafta", "last week"],
  ["gelecek hafta", "next week"],
  ["tarih", "date/history"],
  ["buçuk", "half"],
  ["sık sık", "often/frequently"],
  ["genellikle", "usually/generally"],
  ["her zaman", "always"],
  ["hiçbir zaman", "never"],
  ["sarı", "yellow"],
  ["turuncu", "orange"],
  ["mor", "purple/violet"],
  ["pembe", "pink"],
  ["kahverengi", "brown"],
  ["gri", "grey/gray"],
  ["renk", "color/colour"],
  ["otuz", "thirty"],
  ["kırk", "forty"],
  ["elli", "fifty"],
  ["altmış", "sixty"],
  ["yetmiş", "seventy"],
  ["seksen", "eighty"],
  ["doksan", "ninety"],
  ["elbise", "dress/clothes"],
  ["gömlek", "shirt"],
  ["pantolon", "trousers/pants"],
  ["ceket", "jacket"],
  ["mont", "coat/jacket"],
  ["kazak", "sweater/jumper"],
  ["tişört", "t-shirt"],
  ["ayakkabı", "shoe/shoes"],
  ["çorap", "sock/socks"],
  ["şapka", "hat/cap"],
  ["kemer", "belt"],
  ["yüzük", "ring"],
  ["fiyat", "price"],
  ["ucuz", "cheap"],
  ["pahalı", "expensive"],
  ["indirim", "discount/sale"],
  ["alışveriş", "shopping"],
  ["satmak", "to sell"],
  ["ödemek", "to pay"],
  ["kredi kartı", "credit card"],
  ["nakit", "cash"],
  ["mutluluk", "happiness"],
  ["korkmak", "to be afraid/to fear"],
  ["heyecanlı", "excited/exciting"],
  ["sinirli", "angry/nervous/irritable"],
  ["şaşırmak", "to be surprised"],
  ["utanmak", "to be ashamed/to be embarrassed"],
  ["mutsuz", "unhappy"],
  ["endişeli", "worried/anxious"],
  ["rahatlamak", "to relax"],
  ["sıkılmak", "to be bored/to get bored"],
  ["sevmek", "to love/to like"],
  ["beğenmek", "to like/to admire"],
  ["nefret etmek", "to hate"],
  ["özlemek", "to miss"],
  ["inanmak", "to believe"],
  ["güvenmek", "to trust/to rely on"],
  ["istemek", "to want/to ask for"],
  ["düşünmek", "to think"],
  ["tanımak", "to know/to recognize"],
  ["sanmak", "to think/to suppose"],
  ["hissetmek", "to feel"],
  ["karar vermek", "to decide"],
  ["seçmek", "to choose/to select/to elect"],
  ["denemek", "to try/to test"],
  ["başlamak", "to start/to begin"],
  ["bitirmek", "to finish/to complete"],
  ["bitmek", "to end/to finish/to run out"],
  ["devam etmek", "to continue/to go on"],
  ["beklemek", "to wait/to expect"],
  ["aramak", "to search/to look for/to call"],
  ["kaybetmek", "to lose"],
  ["getirmek", "to bring"],
  ["götürmek", "to take/to carry away"],
  ["taşımak", "to carry/to move"],
  ["koymak", "to put/to place"],
  ["açmak", "to open/to turn on"],
  ["kapatmak", "to close/to shut/to turn off"],
  ["kırmak", "to break"],
  ["kesmek", "to cut"],
  ["izlemek", "to watch/to follow"],
  ["dinlemek", "to listen"],
  ["anlatmak", "to tell/to explain/to describe"],
  ["yardım etmek", "to help"],
  ["şarkı söylemek", "to sing"],
  ["dans etmek", "to dance"],
  ["yüzmek", "to swim"],
  ["içmek", "to drink/to smoke"],
  ["oturmak", "to sit/to live"],
  ["kalkmak", "to get up/to stand up/to depart"],
  ["yatmak", "to lie down/to go to bed"],
  ["doğmak", "to be born/to rise"],
  ["evlenmek", "to get married/to marry"],
  ["boşanmak", "to divorce/to get divorced"],
  ["buluşmak", "to meet/to meet up"],
  ["ziyaret etmek", "to visit"],
  ["davet etmek", "to invite"],
  ["telefon etmek", "to phone/to call"],
  ["göndermek", "to send"],
  ["kullanmak", "to use"],
  ["değiştirmek", "to change"],
  ["temizlemek", "to clean"],
  ["düzeltmek", "to fix/to correct"],
  ["tamir etmek", "to repair/to fix"],
  ["hazırlamak", "to prepare"],
  ["saklamak", "to hide/to keep/to store"],
  ["sevinmek", "to be glad/to be happy/to rejoice"],
  ["öpmek", "to kiss"],
  ["sarılmak", "to hug/to embrace"],
  ["düşmek", "to fall"],
  ["atlamak", "to jump/to skip"],
  ["çekmek", "to pull/to draw/to take a photo"],
  ["itmek", "to push"],
  ["toplamak", "to collect/to gather/to add"],
  ["saymak", "to count/to respect"],
  ["çizmek", "to draw"],
  ["kiralamak", "to rent/to hire"],
  ["paylaşmak", "to share"],
  ["ödünç vermek", "to lend"],
  ["ödünç almak", "to borrow"],
  ["yaklaşmak", "to approach/to come near"],
  ["uzaklaşmak", "to move away"],
  ["geçmek", "to pass/to cross"],
  ["durmak", "to stop/to stand"],
  ["büyümek", "to grow/to grow up"],
  ["artmak", "to increase/to rise"],
  ["azalmak", "to decrease/to diminish"],
  ["ısınmak", "to warm up/to get warm"],
  ["soğumak", "to cool down/to get cold"],
  ["yanmak", "to burn/to be on"],
  ["kızmak", "to get angry"],
  ["şikayet etmek", "to complain"],
  ["teşekkür etmek", "to thank"],
  ["özür dilemek", "to apologize/to apologise"],
  ["affetmek", "to forgive"],
  ["yalan söylemek", "to lie/to tell a lie"],
  ["çevirmek", "to translate/to turn"],
  ["tekrarlamak", "to repeat"],
  ["açıklamak", "to explain/to announce"],
  ["plan", "plan"],
  ["çözüm", "solution"],
  ["çözmek", "to solve/to untie"],
  ["sonuç", "result/conclusion/outcome"],
  ["örnek", "example/sample"],
  ["karışık", "complicated/mixed/messy"],
  ["geniş", "wide/broad/spacious"],
  ["dar", "narrow/tight"],
  ["ince", "thin/fine"],
  ["hafif", "light"],
  ["kirli", "dirty"],
  ["gürültülü", "noisy/loud"],
  ["gürültü", "noise"],
  ["fakir", "poor"],
  ["cömert", "generous"],
  ["modern", "modern"],
  ["geleneksel", "traditional"],
  ["tuzlu", "salty"],
  ["ekşi", "sour"],
  ["taze", "fresh"],
  ["şişman", "fat"],
  ["sarışın", "blonde/blond"],
  ["yumuşak", "soft"],
  ["boş zaman", "free time/leisure"],
  ["hobi", "hobby"],
  ["basketbol", "basketball"],
  ["yüzme", "swimming"],
  ["maç", "match/game"],
  ["film", "film/movie"],
  ["dizi", "series/TV series"],
  ["kamera", "camera"],
  ["gazete", "newspaper"],
  ["dergi", "magazine"],
  ["radyo", "radio"],
  ["bilgisayar", "computer"],
  ["internet", "internet"],
  ["cep telefonu", "mobile phone/cell phone"],
  ["e-posta", "email/e-mail"],
  ["ekran", "screen"],
  ["uygulama", "application/app"],
  ["program", "program/programme"],
  ["video", "video"],
  ["elektrik", "electricity"],
  ["kağıt", "paper"],
  ["kutu", "box"],
  ["paket", "package/packet/parcel"],
  ["kart", "card"],
  ["doğum günü", "birthday"],
  ["bayram", "holiday/festival/feast"],
  ["kutlamak", "to celebrate/to congratulate"],
  ["uyku", "sleep"],
  ["yangın", "fire"],
  ["ambulans", "ambulance"],
  ["tehlike", "danger"],
  ["kural", "rule"],
  ["özgürlük", "freedom/liberty"],
  ["devlet", "state/government"],
  ["hükümet", "government"],
  ["başkent", "capital/capital city"],
  ["halk", "people/public/folk"],
  ["sınır", "border/limit"],
  ["bayrak", "flag"],
  ["din", "religion"],
  ["kültür", "culture"],
  ["gelenek", "tradition"],
  ["çevre", "environment/surroundings"],
  ["kirlilik", "pollution"],
  ["enerji", "energy"],
  ["fatura", "bill/invoice"],
  ["ekonomi", "economy"],
  ["iş yeri", "workplace"],
  ["yorulmak", "to get tired"],
  ["acele etmek", "to hurry"],
  ["geç kalmak", "to be late"],
  ["erken kalkmak", "to get up early"],
  ["alışmak", "to get used to"],
  ["ders çalışmak", "to study"],
  ["başarı", "success"],
  ["amaç", "aim/purpose/goal"],
  ["şimdiki", "present/current"],
  ["dönem", "period/term/era"],
  ["gençlik", "youth"],
  ["çocukluk", "childhood"],
  ["yetişkin", "adult"],
  ["hiç kimse", "nobody/no one"],
  ["bir şey", "something/anything"],
  ["hiçbir şey", "nothing"],
  ["her şey", "everything"],
  ["her yer", "everywhere"],
  ["hızlıca", "quickly"],
  ["yavaşça", "slowly"],
  ["sessizce", "quietly/silently"],
  ["kolayca", "easily"],
  ["maalesef", "unfortunately"],
  ["neyse ki", "fortunately/luckily"],
  ["örneğin", "for example/for instance"],
  ["bu yüzden", "therefore/so/that's why"],
  ["ya da", "or"],
  ["karşısında", "opposite/across from"],
  ["ortasında", "in the middle of"],
  ["etrafında", "around"],
  ["ne zaman", "when"],
  ["ne kadar", "how much/how long"],
  ["hoş geldiniz", "welcome"],
  ["güle güle", "goodbye/bye"],
  ["iyi günler", "good day/have a nice day"],
  ["iyi akşamlar", "good evening"],
  ["iyi geceler", "good night"],
  ["iyi şanslar", "good luck"],
  ["geçmiş olsun", "get well soon/sorry to hear that"],
  ["afiyet olsun", "enjoy your meal/bon appetit"],
  ["kolay gelsin", "take it easy/good luck with your work"],
  ["sağ ol", "thanks/thank you"],
  ["rica ederim", "you're welcome/please/not at all"],
  ["pardon", "excuse me/sorry/pardon"],
  ["inşallah", "hopefully/God willing/I hope so"],
];
